// Yearster Song Database - Auto-generated from verified Spotify data + Hebrew songs
// 600 songs from 1970-2025
// Target: ~100 songs per decade (English + Hebrew)
// Each entry: { id: Spotify Track ID, title, artist, year }

const SONGS = [
  { id: "7iN1s7xHE4ifF5povM6A48", title: "Let It Be - Remastered 2009", artist: "The Beatles", year: 1970 },
  { id: "2LawezPeJhN4AWuSB0GtAU", title: "Have You Ever Seen The Rain", artist: "Creedence Clearwater Revival", year: 1970 },
  { id: "78lgmZwycJ3nzsdgmPPGNx", title: "Immigrant Song - Remaster", artist: "Led Zeppelin", year: 1970 },
  { id: "1jzDzZWeSDBg5fhNc3tczV", title: "Paranoid", artist: "Black Sabbath", year: 1970 },
  { id: "0qdQUeKVyevrbKhAo0ibxS", title: "My Sweet Lord", artist: "George Harrison", year: 1970 },
  { id: "2kkvB3RNRzwjFdGhaUA0tz", title: "Layla - 40th Anniversary Version / 2010 Remastered", artist: "Derek & The Dominos", year: 1970 },
  { id: "1Q5kgpp4pmyGqPwNBzkSrw", title: "Roadhouse Blues", artist: "The Doors", year: 1970 },
  { id: "1gcESexgftSuLuML57Y69q", title: "All Right Now", artist: "Free", year: 1970 },
  { id: "2TVxnKdb3tqe1nhQWwwZCO", title: "Tiny Dancer", artist: "Elton John", year: 1971 },
  { id: "5CQ30WqJwcep0pYcV4AMNc", title: "Stairway to Heaven - Remaster", artist: "Led Zeppelin", year: 1971 },
  { id: "3qiyyUfYe7CRYLucrPmulD", title: "Baba O'Riley", artist: "The Who", year: 1971 },
  { id: "1k1Bqnv2R0uJXQN4u6LKYt", title: "Ain't No Sunshine", artist: "Bill Withers", year: 1971 },
  { id: "14XWXWv5FoCbFzLksawpEe", title: "Riders on the Storm", artist: "The Doors", year: 1971 },
  { id: "3qT4bUD1MaWpGrTwcvguhb", title: "Black Dog - Remaster", artist: "Led Zeppelin", year: 1971 },
  { id: "1fDsrQ23eTAVFElUMaf38X", title: "American Pie", artist: "Don McLean", year: 1971 },
  { id: "52dm9op3rbfAkc1LGXgipW", title: "Wild Horses", artist: "The Rolling Stones", year: 1971 },
  { id: "3gdewACMIVMEWVbyb8O9sY", title: "Rocket Man (I Think It's Going To Be A Long, Long Time)", artist: "Elton John", year: 1972 },
  { id: "54eZmuggBFJbV7k248bTTt", title: "A Horse with No Name", artist: "America", year: 1972 },
  { id: "7Ar4G7Ci11gpt6sfH9Cgz5", title: "Listen to the Music", artist: "The Doobie Brothers", year: 1972 },
  { id: "2DnJjbjNTV9Nd5NOa1KGba", title: "You're so Vain", artist: "Carly Simon", year: 1972 },
  { id: "5MMnwYs0hIxkENRsbkWJ2G", title: "Smoke On The Water - Remastered 2012", artist: "Deep Purple", year: 1972 },
  { id: "4yugZvBYaoREkJKtbG08Qr", title: "Take It Easy - 2013 Remaster", artist: "Eagles", year: 1972 },
  { id: "5p3JunprHCxClJjOmcLV8G", title: "Walk On the Wild Side", artist: "Lou Reed", year: 1972 },
  { id: "0pQskrTITgmCMyr85tb9qq", title: "Starman - 2012 Remaster", artist: "David Bowie", year: 1972 },
  { id: "2BY7ALEWdloFHgQZG6VMLA", title: "Brandy (You're a Fine Girl)", artist: "Looking Glass", year: 1972 },
  { id: "1I7zHEdDx8Ny5RxzYPqsU2", title: "Reelin' In The Years", artist: "Steely Dan", year: 1972 },
  { id: "1Q1b8eVkUPGlpSArl8JAVw", title: "Heart of Gold - 2009 Remaster", artist: "Neil Young", year: 1972 },
  { id: "5MxNLUsfh7uzROypsoO5qe", title: "Dream On", artist: "Aerosmith", year: 1973 },
  { id: "6Ac4NVYYl2U73QiTt11ZKd", title: "Hooked on a Feeling", artist: "Blue Swede", year: 1973 },
  { id: "1bp2IO61zbQrbWNmKKxg3f", title: "The Joker", artist: "Steve Miller Band", year: 1973 },
  { id: "70YvYr2hGlS01bKRIho1HM", title: "La Grange - 2005 Remaster", artist: "ZZ Top", year: 1973 },
  { id: "70C4NyhjD5OZUMzvWZ3njJ", title: "Piano Man", artist: "Billy Joel", year: 1973 },
  { id: "6HSXNV0b4M4cLJ7ljgVVeh", title: "Knockin' On Heaven's Door - Remastered", artist: "Bob Dylan", year: 1973 },
  { id: "0vFOzaXqZHahrZp6enQwQb", title: "Money", artist: "Pink Floyd", year: 1973 },
  { id: "1GcVa4jFySlun4jLSuMhiq", title: "Angie", artist: "The Rolling Stones", year: 1973 },
  { id: "1H4idkmruFoJBg1DvUv2tY", title: "Band On The Run - Remastered 2010", artist: "Paul McCartney", year: 1973 },
  { id: "4nXkbcTj3nyww1cHkw5RAP", title: "Long Train Runnin'", artist: "The Doobie Brothers", year: 1973 },
  { id: "5Wj1rJnCLpMHdLaxsFtJLs", title: "Bennie And The Jets - Remastered 2014", artist: "Elton John", year: 1973 },
  { id: "3TO7bbrUKrOSPGRTB5MeCz", title: "Time", artist: "Pink Floyd", year: 1973 },
  { id: "7e89621JPkKaeDSTQ3avtg", title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974 },
  { id: "2EC9IJj7g0mN1Q5VrZkiYY", title: "Rebel Rebel - 2016 Remaster", artist: "David Bowie", year: 1974 },
  { id: "2SpEHTbUuebeLkgs9QB7Ue", title: "Jolene", artist: "Dolly Parton", year: 1974 },
  { id: "4u7EnebtmKWzUH433cf5Qv", title: "Bohemian Rhapsody - 2011 Mix", artist: "Queen", year: 1975 },
  { id: "5ihS6UUlyQAfmp48eSkxuQ", title: "Landslide", artist: "Fleetwood Mac", year: 1975 },
  { id: "6mFkJmJqdDVQ1REhVfGgd1", title: "Wish You Were Here", artist: "Pink Floyd", year: 1975 },
  { id: "7tFiyTwD0nx5a1eklYtX2J", title: "Bohemian Rhapsody - 2011 Mix", artist: "Queen", year: 1975 },
  { id: "6KTv0Z8BmVqM7DPxbGzpVC", title: "Rock And Roll All Nite", artist: "KISS", year: 1975 },
  { id: "6hTcuIQa0sxrrByu9wTD7s", title: "Born to Run", artist: "Bruce Springsteen", year: 1975 },
  { id: "24NwBd5vZ2CK8VOQVnqdxr", title: "Sweet Emotion", artist: "Aerosmith", year: 1975 },
  { id: "5SZ6zX4rOrEQferfFC2MfP", title: "Walk This Way", artist: "Aerosmith", year: 1975 },
  { id: "714hERk9U1W8FMYkoC83CO", title: "You Sexy Thing", artist: "Hot Chocolate", year: 1975 },
  { id: "7aE5WXu5sFeNRh3Z05wwu4", title: "Wish You Were Here - 2011 Remastered Version", artist: "Pink Floyd", year: 1975 },
  { id: "423hwXFgoN8RYmqLoLuVvY", title: "No Woman, No Cry - Live At The Lyceum, London/1975", artist: "Bob Marley & The Wailers", year: 1975 },
  { id: "40riOy7x9W7GXjyGp4pjAv", title: "Hotel California - 2013 Remaster", artist: "Eagles", year: 1976 },
  { id: "1QEEqeFIZktqIpPI4jSVSF", title: "More Than a Feeling", artist: "Boston", year: 1976 },
  { id: "7LRMbd3LEoV5wZJvXT1Lwb", title: "T.N.T.", artist: "AC/DC", year: 1976 },
  { id: "5QTxFnGygVM4jFQiBovmRo", title: "(Don't Fear) The Reaper", artist: "Blue Öyster Cult", year: 1976 },
  { id: "4DMKwE2E2iYDKY01C335Uw", title: "Carry on Wayward Son", artist: "Kansas", year: 1976 },
  { id: "43DeSV93pJPT4lCZaWZ6b1", title: "The Boys Are Back In Town", artist: "Thin Lizzy", year: 1976 },
  { id: "0KMGxYKeUzK9wc5DZCt3HT", title: "If You Leave Me Now", artist: "Chicago", year: 1976 },
  { id: "2d4e45fmUnguxh6yqC7gNT", title: "Dirty Deeds Done Dirt Cheap", artist: "AC/DC", year: 1976 },
  { id: "7MRyJPksH3G2cXHN8UKYzP", title: "American Girl", artist: "Tom Petty and the Heartbreakers", year: 1976 },
  { id: "6gXrEUzibufX9xYPk3HD5p", title: "Life in the Fast Lane - 2013 Remaster", artist: "Eagles", year: 1976 },
  { id: "4NtUY5IGzHCaqfZemmAu56", title: "Dancing Queen", artist: "ABBA", year: 1976 },
  { id: "4KcH1ZRV2W1q7Flq0QqC76", title: "Blitzkrieg Bop - 2016 Remaster", artist: "Ramones", year: 1976 },
  { id: "0qRR9d89hIS0MHRkQ0ejxX", title: "Rich Girl", artist: "Daryl Hall & John Oates", year: 1976 },
  { id: "4pbJqGIASGPr0ZpGpnWkDn", title: "We Will Rock You - Remastered", artist: "Queen", year: 1977 },
  { id: "2RlgNHKcydI9sayD2Df2xp", title: "Mr. Blue Sky", artist: "Electric Light Orchestra", year: 1977 },
  { id: "0ofHAoxe9vBkTCp2UQIavz", title: "Dreams - 2004 Remaster", artist: "Fleetwood Mac", year: 1977 },
  { id: "5e9TFTbltYBg2xThimr0rU", title: "The Chain - 2004 Remaster", artist: "Fleetwood Mac", year: 1977 },
  { id: "6zeE5tKyr8Nu882DQhhSQI", title: "Dust in the Wind", artist: "Kansas", year: 1977 },
  { id: "1lCRw5FEZ1gPDNPzy1K4zW", title: "We Are The Champions - Remastered 2011", artist: "Queen", year: 1977 },
  { id: "7Jh1bpe76CNTCgdgAdBw4Z", title: "Heroes - 2017 Remaster", artist: "David Bowie", year: 1977 },
  { id: "6XUHsYE38CEbYunT983O9G", title: "Give A Little Bit", artist: "Supertramp", year: 1977 },
  { id: "07GvNcU1WdyZJq3XxP0kZa", title: "Go Your Own Way - 2004 Remaster", artist: "Fleetwood Mac", year: 1977 },
  { id: "4xh7W7tlNMIczFhupCPniY", title: "Go Your Own Way - 2004 Remaster", artist: "Fleetwood Mac", year: 1977 },
  { id: "4KfSdst7rW39C0sfhArdrz", title: "Barracuda", artist: "Heart", year: 1977 },
  { id: "1i6N76fftMZhijOzFQ5ZtL", title: "Psycho Killer - 2005 Remaster", artist: "Talking Heads", year: 1977 },
  { id: "5RgFlk1fcClZd0Y4SGYhqH", title: "She's Always a Woman", artist: "Billy Joel", year: 1977 },
  { id: "2udGjDmpK1dH9VGyw7nrei", title: "Cocaine", artist: "Eric Clapton", year: 1977 },
  { id: "54flyrjcdnQdco7300avMJ", title: "We Will Rock You - Remastered", artist: "Queen", year: 1977 },
  { id: "1JkZg3eMQTmTn93E8Yd3UL", title: "I Want You to Want Me", artist: "Cheap Trick", year: 1977 },
  { id: "5T8EDUDqKcs6OSOwEsfqG7", title: "Don't Stop Me Now - 2011 Mix", artist: "Queen", year: 1978 },
  { id: "3EYOJ48Et32uATr9ZmLnAo", title: "Roxanne", artist: "The Police", year: 1978 },
  { id: "4aVuWgvD0X63hcOCnZtNFA", title: "Hold the Line", artist: "TOTO", year: 1978 },
  { id: "7hQJA50XrCWABAu5v6QZ4i", title: "Don't Stop Me Now - 2011 Mix", artist: "Queen", year: 1978 },
  { id: "5EOoMWIB9iK4ZpcSex9Ec7", title: "Old Time Rock & Roll", artist: "Bob Seger", year: 1978 },
  { id: "3KhF2YiNpJvGpfiCW45R6D", title: "Runnin' with the Devil - 2015 Remaster", artist: "Van Halen", year: 1978 },
  { id: "2zYzyRzz6pRmhPzyfMEC8s", title: "Highway to Hell", artist: "AC/DC", year: 1979 },
  { id: "07q0QVgO56EorrSGHC48y3", title: "I Was Made For Lovin' You", artist: "KISS", year: 1979 },
  { id: "4gMgiXfqyzZLMhsksGmbQV", title: "Another Brick in the Wall, Pt. 2", artist: "Pink Floyd", year: 1979 },
  { id: "5HNCy40Ni5BZJFw1TKzRsC", title: "Comfortably Numb", artist: "Pink Floyd", year: 1979 },
  { id: "1oYYd2gnWZYrt89EBXdFiO", title: "Message In A Bottle", artist: "The Police", year: 1979 },
  { id: "1QFh8OH1e78dGd3VyJZCAC", title: "Boys Don't Cry", artist: "The Cure", year: 1979 },
  { id: "1HOMkjp0nHMaTnfAkslCQj", title: "My Sharona", artist: "The Knack", year: 1979 },
  { id: "5jzma6gCzYtKB1DbEwFZKH", title: "London Calling - Remastered", artist: "The Clash", year: 1979 },
  { id: "5IMtdHjJ1OtkxbGe4zfUxQ", title: "Escape (The Pina Colada Song)", artist: "Rupert Holmes", year: 1979 },
  { id: "6mHOcVtsHLMuesJkswc0GZ", title: "The Logical Song - Remastered 2010", artist: "Supertramp", year: 1979 },
  { id: "5IKLwqBQG6KU6MP2zP80Nu", title: "We Are Family", artist: "Sister Sledge", year: 1979 },
  { id: "72ahyckBJfTigJCFCviVN7", title: "Don't Bring Me Down", artist: "Electric Light Orchestra", year: 1979 },
  { id: "08mG3Y1vljYA6bvDt4Wqkj", title: "Back In Black", artist: "AC/DC", year: 1980 },
  { id: "5vdp5UmvTsnMEMESIF2Ym7", title: "Another One Bites The Dust - Remastered 2011", artist: "Queen", year: 1980 },
  { id: "2SiXAy7TuUkycRVbbWDEpo", title: "You Shook Me All Night Long", artist: "AC/DC", year: 1980 },
  { id: "2b9lp5A6CqSzwOrBfAFhof", title: "Crazy Train", artist: "Ozzy Osbourne", year: 1980 },
  { id: "4o6BgsqLIBViaGVbx5rbRk", title: "You Make My Dreams", artist: "Daryl Hall & John Oates", year: 1980 },
  { id: "6xdLJrVj4vIXwhuG8TMopk", title: "Crazy Little Thing Called Love - Remastered 2011", artist: "Queen", year: 1980 },
  { id: "57JVGBtBLCfHw2muk5416J", title: "Another One Bites The Dust - Remastered 2011", artist: "Queen", year: 1980 },
  { id: "6EPRKhUOdiFSQwGBRBbvsZ", title: "Ace of Spades", artist: "Motörhead", year: 1980 },
  { id: "71SvEDmsOwIWw1IozsZoMA", title: "Any Way You Want It", artist: "Journey", year: 1980 },
  { id: "7o7E1nrHWncYY7PY94gCiX", title: "Video Killed The Radio Star", artist: "The Buggles", year: 1980 },
  { id: "4rcHWl68ai6KvpXlc8vbnE", title: "Keep on Loving You", artist: "REO Speedwagon", year: 1980 },
  { id: "4bHsxqR3GMrXTxEPLuK5ue", title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
  { id: "7HKez549fwJQDzx3zLjHKC", title: "Start Me Up - Remastered", artist: "The Rolling Stones", year: 1981 },
  { id: "18AXbzPzBS8Y3AkgSxzJPb", title: "In The Air Tonight - 2015 Remastered", artist: "Phil Collins", year: 1981 },
  { id: "3L7RtEcu1Hw3OXrpnthngx", title: "Don't You Want Me", artist: "The Human League", year: 1981 },
  { id: "0cGG2EouYCEEC3xfa0tDFV", title: "Tainted Love", artist: "Soft Cell", year: 1981 },
  { id: "3QZ7uX97s82HFYSmQUAN1D", title: "Tom Sawyer", artist: "Rush", year: 1981 },
  { id: "2Cdvbe2G4hZsnhNMKyGrie", title: "I Love Rock 'N Roll", artist: "Joan Jett & The Blackhearts", year: 1981 },
  { id: "0qi4b1l0eT3jpzeNHeFXDT", title: "Just Can't Get Enough", artist: "Depeche Mode", year: 1981 },
  { id: "1ynmMEK1fkyiZ6Z6F3ThEt", title: "Centerfold", artist: "The J. Geils Band", year: 1981 },
  { id: "5RsUlxLto4NZbhJpqJbHfN", title: "Jessie's Girl", artist: "Rick Springfield", year: 1981 },
  { id: "2374M0fQpWi3dLnB54qaLX", title: "Africa", artist: "TOTO", year: 1982 },
  { id: "5ChkMS8OtdzJeqyybCc9R5", title: "Billie Jean", artist: "Michael Jackson", year: 1982 },
  { id: "2fuCquhmrzHpu5xcA1ci9x", title: "Under Pressure - Remastered", artist: "Queen", year: 1982 },
  { id: "39shmbIHICJ2Wxnk1fPSdz", title: "Should I Stay or Should I Go - Remastered", artist: "The Clash", year: 1982 },
  { id: "1OOtq8tRnDM8kG2gqUPjAj", title: "Beat It - Single Version", artist: "Michael Jackson", year: 1982 },
  { id: "43btz2xjMKpcmjkuRsvxyg", title: "Jack & Diane", artist: "John Mellencamp", year: 1982 },
  { id: "2HHtWyy5CgaQbC7XSoOb0e", title: "Eye of the Tiger", artist: "Survivor", year: 1982 },
  { id: "56KqaFSGTb7ifpt16t5Y1N", title: "Rock the Casbah - Remastered", artist: "The Clash", year: 1982 },
  { id: "39lSeqnyjZJejRuaREfyLL", title: "Hungry Like the Wolf - 2009 Remaster", artist: "Duran Duran", year: 1982 },
  { id: "5lA3pwMkBdd24StM90QrNR", title: "P.Y.T. (Pretty Young Thing)", artist: "Michael Jackson", year: 1982 },
  { id: "1JSTJqkT5qHq8MDJnJbRE1", title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { id: "1TfqLAPs4K3s2rJMoCokcS", title: "Sweet Dreams (Are Made of This) - Remastered", artist: "Eurythmics", year: 1983 },
  { id: "5zA8vzDGqPl2AzZkEYQGKh", title: "Uptown Girl", artist: "Billy Joel", year: 1983 },
  { id: "4y1LsJpmMti1PfRQV9AWWe", title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
  { id: "4ZhPLoMzZwewHLLjV1J15c", title: "99 Luftballons", artist: "Nena", year: 1983 },
  { id: "1UBQ5GK8JaQjm5VbkBZY66", title: "Sharp Dressed Man - 2008 Remaster", artist: "ZZ Top", year: 1983 },
  { id: "6C4LXC9UFH1IKiHYOp0BiJ", title: "Sunday Bloody Sunday - Remastered 2008", artist: "U2", year: 1983 },
  { id: "2wSAWEYUHkt92X4SBAPqZE", title: "Karma Chameleon - Remastered", artist: "Culture Club", year: 1983 },
  { id: "4TIJ7zSBNejpoIPaWpWRKc", title: "Rebel Yell", artist: "Billy Idol", year: 1983 },
  { id: "3ix6K4wZY29bCujrSznwFZ", title: "Let's Dance - 2018 Remaster", artist: "David Bowie", year: 1983 },
  { id: "7N3PAbqfTjSEU1edb2tY8j", title: "Jump - 2015 Remaster", artist: "Van Halen", year: 1984 },
  { id: "1JLn8RhQzHz3qDqsChcmBl", title: "I Want to Know What Love Is - 1999 Remaster", artist: "Foreigner", year: 1984 },
  { id: "4gvea7UlDkAvsJBPZAd4oB", title: "The Boys Of Summer", artist: "Don Henley", year: 1984 },
  { id: "7FwBtcecmlpc1sLySPXeGE", title: "Dancing In the Dark", artist: "Bruce Springsteen", year: 1984 },
  { id: "0dOg1ySSI7NkpAe89Zo0b9", title: "Born in the U.S.A.", artist: "Bruce Springsteen", year: 1984 },
  { id: "1hlveB9M6ijHZRbzZ2teyh", title: "We're Not Gonna Take It", artist: "Twisted Sister", year: 1984 },
  { id: "5WwqdeavrQrbeAMDxGawse", title: "Can't Fight This Feeling", artist: "REO Speedwagon", year: 1984 },
  { id: "3PzsbWSQdLCKDLxn7YZfkM", title: "I'm On Fire", artist: "Bruce Springsteen", year: 1984 },
  { id: "05RgAMGypEvqhNs5hPCbMS", title: "Panama - 2015 Remaster", artist: "Van Halen", year: 1984 },
  { id: "36lkJSDyMEZoWTqtRj8Q8q", title: "You're the Inspiration - 2006 Remaster", artist: "Chicago", year: 1984 },
  { id: "1FvDJ9KGxcqwv1utyPL3JZ", title: "This Charming Man - 2011 Remaster", artist: "The Smiths", year: 1984 },
  { id: "2WfaOiMkCvy7F5fcp2zZ8L", title: "Take on Me", artist: "a-ha", year: 1985 },
  { id: "4RvWPyQ5RL0ao9LPZeSouE", title: "Everybody Wants To Rule The World", artist: "Tears For Fears", year: 1985 },
  { id: "2KH16WveTQWT6KOG9Rg6e2", title: "Eye of the Tiger", artist: "Survivor", year: 1985 },
  { id: "3Ud6fFep5ZlXzRWw6Sm8no", title: "Walk Of Life", artist: "Dire Straits", year: 1985 },
  { id: "4oDZ5L8izBals6jKBJDBcX", title: "Your Love", artist: "The Outfield", year: 1985 },
  { id: "5dRQUolXAVX3BbCiIxmSsf", title: "Your Love", artist: "The Outfield", year: 1985 },
  { id: "4zXvB4MoQD8onk0NCZbeHG", title: "Home Sweet Home", artist: "Mötley Crüe", year: 1985 },
  { id: "37ZJ0p5Jm13JPevGcx4SkF", title: "Livin' On A Prayer", artist: "Bon Jovi", year: 1986 },
  { id: "2pnPe4pJtq7689i5ydzvJJ", title: "Run Rudolph Run - Single Version", artist: "Chuck Berry", year: 1986 },
  { id: "3MrRksHupTVEQ7YbA0FsZK", title: "The Final Countdown", artist: "Europe", year: 1986 },
  { id: "0qxYx4F3vm1AOnfux6dDxP", title: "You Can Call Me Al", artist: "Paul Simon", year: 1986 },
  { id: "62LJFaYihsdVrrkgUOJC05", title: "Kiss", artist: "Prince", year: 1986 },
  { id: "0WQiDwKJclirSYG9v5tayI", title: "There Is a Light That Never Goes Out - 2011 Remaster", artist: "The Smiths", year: 1986 },
  { id: "6yl8Es1tCYD9WdSkeVLFw4", title: "You Shook Me All Night Long", artist: "AC/DC", year: 1986 },
  { id: "7G7tgVYORlDuVprcYHuFJh", title: "Don't Dream It's Over", artist: "Crowded House", year: 1986 },
  { id: "4ByEFOBuLXpCqvO1kw8Wdm", title: "(I Just) Died In Your Arms", artist: "Cutting Crew", year: 1986 },
  { id: "1eyq8cjUQ2daFthW2PC2GM", title: "Glory of Love", artist: "Peter Cetera", year: 1986 },
  { id: "7o2CTH4ctstm8TNelqjb51", title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { id: "2tUBqZG2AbRi7Q0BIrVrEj", title: "I Wanna Dance with Somebody (Who Loves Me)", artist: "Whitney Houston", year: 1987 },
  { id: "6ADSaE87h8Y3lccZlBJdXH", title: "With Or Without You - Remastered", artist: "U2", year: 1987 },
  { id: "0bVtevEgtDIeRjCJbK3Lmv", title: "Welcome To The Jungle", artist: "Guns N' Roses", year: 1987 },
  { id: "3YBZIN3rekqsKxbJc9FZko", title: "Paradise City", artist: "Guns N' Roses", year: 1987 },
  { id: "1uKjQoh8JZj9ryuYRhpd7E", title: "Ahora Te Puedes Marchar", artist: "Luis Miguel", year: 1987 },
  { id: "6wpGqhRvJGNNXwWlPmkMyO", title: "I Still Haven't Found What I'm Looking For", artist: "U2", year: 1987 },
  { id: "0HEmnAUT8PHznIAAmVXqFJ", title: "Faith - Remastered", artist: "George Michael", year: 1987 },
  { id: "0PdM2a6oIjqepoEfcJo0RO", title: "Pour Some Sugar On Me - Remastered 2017", artist: "Def Leppard", year: 1987 },
  { id: "54b8qPFqYqIndfdxiLApea", title: "Alone", artist: "Heart", year: 1987 },
  { id: "4mn2kNTqiGLwaUR8JdhJ1l", title: "The House of the Rising Sun", artist: "The Animals", year: 1987 },
  { id: "4KFM3A5QF2IMcc6nHsu3Wp", title: "Englishman In New York", artist: "Sting", year: 1987 },
  { id: "5xLyTbCFONUGUuG0LtUxjn", title: "Girls, Girls, Girls", artist: "Mötley Crüe", year: 1987 },
  { id: "6Nd6ntkzr4t8o1FKPGOSMt", title: "Here I Go Again - 2018 Remaster", artist: "Whitesnake", year: 1987 },
  { id: "2M9ro2krNb7nr7HSprkEgo", title: "Fast Car", artist: "Tracy Chapman", year: 1988 },
  { id: "78TnMTAFmWUWWCgNXR7D3K", title: "Listen to Your Heart", artist: "Roxette", year: 1988 },
  { id: "6F9yAYUaNbUhdlQyt5uZ3b", title: "La Incondicional", artist: "Luis Miguel", year: 1988 },
  { id: "6mcxQ1Y3uQRU0IHsvdNLH1", title: "Where Is My Mind?", artist: "Pixies", year: 1988 },
  { id: "7BwxbmYFy0l3ROHDjV2c14", title: "Culpable O No - Miénteme Como Siempre", artist: "Luis Miguel", year: 1988 },
  { id: "0ZfM5XfJTtFPhOxAERRnNY", title: "The Look", artist: "Roxette", year: 1988 },
  { id: "43GS3mtezoIFiuIZCLLiDY", title: "Every Rose Has Its Thorn - Remastered 2003", artist: "Poison", year: 1988 },
  { id: "2QgWuCtBpNIpl5trmKCxRf", title: "American Pie", artist: "Don McLean", year: 1988 },
  { id: "4d6eqRtpDX7tydHJGDZUBQ", title: "She Drives Me Crazy", artist: "Fine Young Cannibals", year: 1988 },
  { id: "6KIKRz9eSTXdNsGUnomdtW", title: "Straight Outta Compton", artist: "N.W.A.", year: 1988 },
  { id: "7GonnnalI2s19OCQO1J7Tf", title: "Kickstart My Heart", artist: "Mötley Crüe", year: 1989 },
  { id: "5tVA6TkbaAH9QMITTQRrNv", title: "Free Fallin'", artist: "Tom Petty", year: 1989 },
  { id: "4LFwNJWoj74Yd71fIr1W8x", title: "Right Here Waiting", artist: "Richard Marx", year: 1989 },
  { id: "3Cx4yrFaX8CeHwBMReOWXI", title: "We Didn't Start the Fire", artist: "Billy Joel", year: 1989 },
  { id: "6mYrhCAGWzTdF8QnKuchXM", title: "If I Could Turn Back Time", artist: "Cher", year: 1989 },
  { id: "7gSQv1OHpkIoAdUiRLdmI6", title: "I Won't Back Down", artist: "Tom Petty", year: 1989 },
  { id: "5XcZRgJv3zMhTqCyESjQrF", title: "Poison", artist: "Alice Cooper", year: 1989 },
  { id: "57bgtoPSgt236HzfBOd8kj", title: "Thunderstruck", artist: "AC/DC", year: 1990 },
  { id: "3ovjw5HZZv43SxTwApooCM", title: "Wind Of Change", artist: "Scorpions", year: 1990 },
  { id: "2SbsvihBJmgNKZ4qkXFWrp", title: "More Than Words", artist: "Extreme", year: 1990 },
  { id: "38xhBO2AKrJnjdjVnhJES6", title: "This Christmas", artist: "Donny Hathaway", year: 1990 },
  { id: "2nejvFyJeTDtMRP2nUMt0J", title: "Abrázame Muy Fuerte", artist: "Juan Gabriel", year: 1990 },
  { id: "31AOj9sFz2gM0O3hMARRBx", title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
  { id: "3d9DChrdc6BOeFsbrZ3Is0", title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1991 },
  { id: "1f3yAtsJtY87CTmM8RLnxf", title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { id: "5sICkBXVmaCQk5aISGR3x1", title: "Enter Sandman", artist: "Metallica", year: 1991 },
  { id: "3G69vJMWsX6ZohTykad2AU", title: "One", artist: "U2", year: 1991 },
  { id: "4JiEyzf0Md7KEFFGWDDdCr", title: "Knockin' On Heaven's Door", artist: "Guns N' Roses", year: 1991 },
  { id: "6QewNVIDKdSl8Y3ycuHIei", title: "Even Flow", artist: "Pearl Jam", year: 1991 },
  { id: "1L94M3KIu7QluZe63g64rv", title: "Alive", artist: "Pearl Jam", year: 1991 },
  { id: "5Xak5fmy089t0FYmh3VJiY", title: "Black", artist: "Pearl Jam", year: 1991 },
  { id: "2N2yrmodOnVF10mKvItC9P", title: "Don't Cry (Original)", artist: "Guns N' Roses", year: 1991 },
  { id: "5ghIJDpPoe3CfHMGu71E6T", title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { id: "1Eb90nmqTrxylKFhcUzW8P", title: "(Everything I Do) I Do It For You", artist: "Bryan Adams", year: 1991 },
  { id: "5BIMPccDwShpXq784RJlJp", title: "Enter Sandman", artist: "Metallica", year: 1991 },
  { id: "0uppYCG86ajpV2hSR3dJJ0", title: "Give It Away", artist: "Red Hot Chili Peppers", year: 1991 },
  { id: "4aYLAF6ckQ5ooGGGM7sWAa", title: "The Unforgiven", artist: "Metallica", year: 1991 },
  { id: "4P5KoWXOxwuobLmHXLMobV", title: "Come As You Are", artist: "Nirvana", year: 1991 },
  { id: "59WN2psjkt1tyaxjspN8fp", title: "Killing In The Name", artist: "Rage Against The Machine", year: 1992 },
  { id: "4QlzkaRHtU8gAdwqjWmO8n", title: "Friday I'm In Love", artist: "The Cure", year: 1992 },
  { id: "2qOm7ukLyHUXWyR4ZWLwxA", title: "It Was A Good Day", artist: "Ice Cube", year: 1992 },
  { id: "3TZwjdclvWt7iPJUnMpgcs", title: "Jump Around", artist: "House Of Pain", year: 1992 },
  { id: "6PypGyiu0Y2lCDBN1XZEnP", title: "Everybody Hurts", artist: "R.E.M.", year: 1992 },
  { id: "1zng9uqqXoPkmU05nsAlsw", title: "Bed Of Roses", artist: "Bon Jovi", year: 1992 },
  { id: "612VcBshQcy4mpB2utGc3H", title: "Tears in Heaven - Acoustic; Live at MTV Unplugged, Bray Film Studios, Windsor, England, UK, 1/16/1992; 2013 Remaster", artist: "Eric Clapton", year: 1992 },
  { id: "6txWz9UapYHVxEd7dDIHXT", title: "No Rain", artist: "Blind Melon", year: 1992 },
  { id: "31er9IGsfFbwqy1pH4aiTP", title: "I Have Nothing", artist: "Whitney Houston", year: 1992 },
  { id: "7fcfNW0XxTWlwVlftzfDOR", title: "Walk", artist: "Pantera", year: 1992 },
  { id: "6b2oQwSGFkzsMtQruIWm2p", title: "Creep", artist: "Radiohead", year: 1993 },
  { id: "0gEyKnHvgkrkBM6fbeHdwK", title: "Linger", artist: "The Cranberries", year: 1993 },
  { id: "11LmqTE2naFULdEP94AUBa", title: "Heart-Shaped Box", artist: "Nirvana", year: 1993 },
  { id: "0WKYRFtH6KKbaNWjsxqm70", title: "Gin And Juice (feat. Dat Nigga Daz)", artist: "Snoop Dogg", year: 1993 },
  { id: "45Ia1U4KtIjAPPU7Wv1Sea", title: "Are You Gonna Go My Way", artist: "Lenny Kravitz", year: 1993 },
  { id: "119c93MHjrDLJTApCVGpvx", title: "C.R.E.A.M.", artist: "Wu-Tang Clan", year: 1993 },
  { id: "4JGKZS7h4Qa16gOU3oNETV", title: "Dreams", artist: "The Cranberries", year: 1993 },
  { id: "0wokCRaKD0zPNhMRXAgVsr", title: "Ordinary World", artist: "Duran Duran", year: 1993 },
  { id: "6CKoWCWAqEVWVjpeoJXyNH", title: "Shape Of My Heart", artist: "Sting", year: 1993 },
  { id: "0bYg9bo50gSsH3LtXe2SQn", title: "All I Want for Christmas Is You", artist: "Mariah Carey", year: 1994 },
  { id: "2IZZqH4K02UIYg5EohpNHF", title: "Zombie", artist: "The Cranberries", year: 1994 },
  { id: "6L89mwZXSOwYl76YXfX13s", title: "Basket Case", artist: "Green Day", year: 1994 },
  { id: "5ByAIlEEnxYdvpnezg7HTX", title: "Juicy - 2005 Remaster", artist: "The Notorious B.I.G.", year: 1994 },
  { id: "1Dr1fXbc2IxaK1Mu8P8Khz", title: "When I Come Around", artist: "Green Day", year: 1994 },
  { id: "2g8HN35AnVGIk7B8yMucww", title: "Big Poppa - 2005 Remaster", artist: "The Notorious B.I.G.", year: 1994 },
  { id: "7nYvUtkQMx1v80S2FH2s9J", title: "Regulate", artist: "Warren G", year: 1994 },
  { id: "6VoIBz0VhCyz7OdEoRYDiA", title: "Say It Ain't So", artist: "Weezer", year: 1994 },
  { id: "3pRaLNL3b8x5uBOcsgvdqM", title: "Hallelujah", artist: "Jeff Buckley", year: 1994 },
  { id: "15VRO9CQwMpbqUYA7e6Hwg", title: "The Man Who Sold The World", artist: "Nirvana", year: 1994 },
  { id: "7lQWRAjyhTpCWFC0jmclT4", title: "Gangsta's Paradise", artist: "Coolio", year: 1995 },
  { id: "5qqabIl2vWzo9ApSC317sa", title: "Wonderwall - Remastered", artist: "Oasis", year: 1995 },
  { id: "5QLHGv0DfpeXLNFo7SFEy1", title: "1979 - Remastered 2012", artist: "The Smashing Pumpkins", year: 1995 },
  { id: "4IYKjN1DrYzxKXt0umJqsG", title: "I Got 5 On It", artist: "Luniz", year: 1995 },
  { id: "33ZXjLCpiINn8eQIDYEPTD", title: "Shook Ones, Pt. II", artist: "Mobb Deep", year: 1995 },
  { id: "7H8zey5My6uNdD2TxeCb9F", title: "Don't Speak", artist: "No Doubt", year: 1995 },
  { id: "0UvCh63URrLFcPkKt99hHd", title: "Don't Look Back in Anger - Remastered", artist: "Oasis", year: 1995 },
  { id: "2aBxt229cbLDOvtL7Xbb9x", title: "Always Be My Baby", artist: "Mariah Carey", year: 1995 },
  { id: "5jafMI8FLibnjkYTZ33m0c", title: "High And Dry", artist: "Radiohead", year: 1995 },
  { id: "1Je1IMUlBXcx1Fz0WE7oPT", title: "Wannabe", artist: "Spice Girls", year: 1996 },
  { id: "3ssX20QT5c3nA9wk78V1LQ", title: "Ambitionz Az A Ridah", artist: "2Pac", year: 1996 },
  { id: "6MdqqkQ8sSC0WB4i8PyRuQ", title: "No Diggity", artist: "Blackstreet", year: 1996 },
  { id: "2xTft6GEZeTyWNpdX94rkf", title: "All Eyez On Me", artist: "2Pac", year: 1996 },
  { id: "0Q0IVlqMV64kNLlwjPj0Hl", title: "Killing Me Softly With His Song", artist: "Fugees", year: 1996 },
  { id: "46RVKt5Edm1zl0rXhPJZxz", title: "Down Under", artist: "Men At Work", year: 1996 },
  { id: "0tZ3mElWcr74OOhKEiNz1x", title: "Bulls On Parade", artist: "Rage Against The Machine", year: 1996 },
  { id: "57iDDD9N9tTWe75x6qhStw", title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997 },
  { id: "5UWwZ5lm5PKu6eKsHAGxOk", title: "Everlong", artist: "Foo Fighters", year: 1997 },
  { id: "7KwZNVEaqikRSBSpyhXK2j", title: "Hypnotize - 2014 Remaster", artist: "The Notorious B.I.G.", year: 1997 },
  { id: "6ORqU0bHbVCRjXm9AjyHyZ", title: "Good Riddance (Time of Your Life)", artist: "Green Day", year: 1997 },
  { id: "1FTSo4v6BOZH9QxKc3MbVM", title: "Song 2 - 2012 Remaster", artist: "Blur", year: 1997 },
  { id: "3SVAN3BRByDmHOhKyIDxfC", title: "Karma Police", artist: "Radiohead", year: 1997 },
  { id: "42et6fnHCw1HIPSrdPprMl", title: "Semi-Charmed Life", artist: "Third Eye Blind", year: 1997 },
  { id: "0wQCKR9OFjYu5Kzrk7WivJ", title: "Corazón partío", artist: "Alejandro Sanz", year: 1997 },
  { id: "1M2nd8jNUkkwrc1dgBPTJz", title: "Angels", artist: "Robbie Williams", year: 1997 },
  { id: "4INDiWSKvqSKDEu7mh8HFz", title: "Mo Money Mo Problems (feat. Puff Daddy & Mase) - 2014 Remaster", artist: "The Notorious B.I.G.", year: 1997 },
  { id: "0mvocLIWUnT10znvIXwHGr", title: "En El Muelle De San Blas", artist: "Maná", year: 1997 },
  { id: "6Qyc6fS4DsZjB2mRW9DsQs", title: "Iris", artist: "The Goo Goo Dolls", year: 1998 },
  { id: "2goLsvvODILDzeeiT4dAoR", title: "Believe", artist: "Cher", year: 1998 },
  { id: "4EchqUKQ3qAQuRNKmeIpnf", title: "The Kids Aren't Alright", artist: "The Offspring", year: 1998 },
  { id: "225xvV8r1yKMHErSWivnow", title: "I Don't Want to Miss a Thing - From Armageddon Soundtrack", artist: "Aerosmith", year: 1998 },
  { id: "4jDmJ51x1o9NZB5Nxxc7gY", title: "Careless Whisper", artist: "George Michael", year: 1998 },
  { id: "0c1gHntWjKD7QShC8s99sq", title: "I Don't Want to Miss a Thing - From the Touchstone film, Armageddon", artist: "Aerosmith", year: 1998 },
  { id: "1Cwsd5xI8CajJz795oy4XF", title: "You Get What You Give", artist: "New Radicals", year: 1998 },
  { id: "6W21LNLz9Sw7sUSNWMSHRu", title: "Freak On a Leash", artist: "Korn", year: 1998 },
  { id: "48UPSzbZjgc449aqz8bxox", title: "Californication", artist: "Red Hot Chili Peppers", year: 1999 },
  { id: "3cfOd4CMv2snFaKAnMdnvK", title: "All Star", artist: "Smash Mouth", year: 1999 },
  { id: "1KGi9sZVMeszgZOWivFpxs", title: "No Scrubs", artist: "TLC", year: 1999 },
  { id: "64BbK9SFKH2jk86U3dGj2P", title: "Otherside", artist: "Red Hot Chili Peppers", year: 1999 },
  { id: "2m1hi0nfMR9vdGC8UcrnwU", title: "All The Small Things", artist: "blink-182", year: 1999 },
  { id: "1G391cbiT3v3Cywg8T7DM1", title: "Scar Tissue", artist: "Red Hot Chili Peppers", year: 1999 },
  { id: "6x4tKaOzfNJpEJHySoiJcs", title: "Mambo No. 5 (a Little Bit of...)", artist: "Lou Bega", year: 1999 },
  { id: "7H6ev70Weq6DdpZyyTmUXk", title: "Say My Name", artist: "Destiny's Child", year: 1999 },
  { id: "3MjUtNVVq3C8Fn0MP3zhXa", title: "...Baby One More Time", artist: "Britney Spears", year: 1999 },
  { id: "503OTo2dSqe7qk76rgsbep", title: "Still D.R.E.", artist: "Dr. Dre", year: 1999 },
  { id: "5prTs2HAw2G4idHZyeFp8o", title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", year: 1999 },
  { id: "7nnWIPM5hwE3DaUBkvOIpy", title: "Drive", artist: "Incubus", year: 1999 },
  { id: "5OQsiBsky2k2kDKy2bX2eT", title: "Learn to Fly", artist: "Foo Fighters", year: 1999 },
  { id: "2eknDuc5IeulN0hnwEZsjF", title: "The Next Episode", artist: "Dr. Dre", year: 1999 },
  { id: "6mz1fBdKATx6qP4oP1I65G", title: "Pony", artist: "Ginuwine", year: 1999 },
  { id: "60a0Rd6pjrkxjPbaKzXjfq", title: "In the End", artist: "Linkin Park", year: 2000 },
  { id: "3AJwUDP919kvQ9QcozQPxg", title: "Yellow", artist: "Coldplay", year: 2000 },
  { id: "3yfqSUWxFvZELEM4PmlwIR", title: "The Real Slim Shady", artist: "Eminem", year: 2000 },
  { id: "0I3q5fE6wg7LIfHGngUTnV", title: "Ms. Jackson", artist: "OutKast", year: 2000 },
  { id: "6ZOBP3NvffbU4SZcrnt1k6", title: "Kryptonite", artist: "3 Doors Down", year: 2000 },
  { id: "6naxalmIoLFWR0siv8dnQQ", title: "Oops!...I Did It Again", artist: "Britney Spears", year: 2000 },
  { id: "2DlHlPMa4M17kufBvI2lEN", title: "Chop Suey!", artist: "System Of A Down", year: 2001 },
  { id: "5W8YXBz9MTIDyrpYaCg2Ky", title: "Last Resort", artist: "Papa Roach", year: 2001 },
  { id: "0gmbgwZ8iqyMPmXefof8Yf", title: "How You Remind Me", artist: "Nickelback", year: 2001 },
  { id: "0snQkGI5qnAmohLE7jTsTn", title: "Toxicity", artist: "System Of A Down", year: 2001 },
  { id: "2hKdd3qO7cWr2Jo0Bcs0MA", title: "Drops of Jupiter", artist: "Train", year: 2001 },
  { id: "7vFv0yFGMJW3qVXbAd9BK9", title: "Your Body Is a Wonderland", artist: "John Mayer", year: 2001 },
  { id: "6e40mgJiCid5HRAGrbpGA6", title: "I Want It That Way", artist: "Backstreet Boys", year: 2001 },
  { id: "2MLHyLy5z5l5YRp7momlgw", title: "Island In The Sun", artist: "Weezer", year: 2001 },
  { id: "0DiWol3AO6WpXZgp0goxAV", title: "One More Time", artist: "Daft Punk", year: 2001 },
  { id: "77NNZQSqzLNqh2A9JhLRkg", title: "Don't Stop Believin'", artist: "Journey", year: 2001 },
  { id: "75JFxkI2RXiU7L9VXzMkle", title: "The Scientist", artist: "Coldplay", year: 2002 },
  { id: "4xkOaSrkexMciUUogZKVTS", title: "'Till I Collapse", artist: "Eminem", year: 2002 },
  { id: "4llK75pXNWZz6KAho2Gp16", title: "She Will Be Loved - Radio Mix", artist: "Maroon 5", year: 2002 },
  { id: "3ZOEytgrvLwQaqXreDs2Jx", title: "Can't Stop", artist: "Red Hot Chili Peppers", year: 2002 },
  { id: "5xEM5hIgJ1jjgcEBfpkt2F", title: "Complicated", artist: "Avril Lavigne", year: 2002 },
  { id: "0ARK753YaiJbpLUk7z5yIM", title: "Dilemma", artist: "Nelly", year: 2002 },
  { id: "4w1lzcaoZ1IC2K5TwjalRP", title: "A Thousand Miles", artist: "Vanessa Carlton", year: 2002 },
  { id: "6ECp64rv50XVz93WvxXMGF", title: "This Love", artist: "Maroon 5", year: 2002 },
  { id: "0BCPKOYdS2jbQ8iyB56Zns", title: "Clocks", artist: "Coldplay", year: 2002 },
  { id: "3YuaBvuZqcwN3CEAyyoaei", title: "Like a Stone", artist: "Audioslave", year: 2002 },
  { id: "3NLrRZoMF0Lx6zTlYqeIo4", title: "Here Without You", artist: "3 Doors Down", year: 2002 },
  { id: "7Lf7oSEVdzZqTA0kEDSlS5", title: "Cry Me a River", artist: "Justin Timberlake", year: 2002 },
  { id: "2nLtzopw4rPReszdYBJU6h", title: "Numb", artist: "Linkin Park", year: 2003 },
  { id: "6I9VzXrHxO9rA9A5euc8Ak", title: "Toxic", artist: "Britney Spears", year: 2003 },
  { id: "47wPvRG8FEwbZP22UBgTQr", title: "Seven Nation Army", artist: "The White Stripes", year: 2003 },
  { id: "0COqiPhxzoWICwFCS4eZcp", title: "Bring Me To Life", artist: "Evanescence", year: 2003 },
  { id: "2PpruBYCo4H7WOBJ7Q2EwM", title: "Hey Ya!", artist: "OutKast", year: 2003 },
  { id: "3XVBdLihbNbxUwZosxcGuJ", title: "If I Ain't Got You", artist: "Alicia Keys", year: 2003 },
  { id: "7iL6o9tox1zgHpKUfh9vuC", title: "In Da Club", artist: "50 Cent", year: 2003 },
  { id: "5IVuqXILoxVWvWEPm82Jxr", title: "Crazy In Love (feat. Jay-Z)", artist: "Beyoncé", year: 2003 },
  { id: "66S14BkJDxgkYxLl5DCqOz", title: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers", year: 2003 },
  { id: "5rb9QrpfcKFHM1EUbSIurX", title: "Yeah! (feat. Lil Jon & Ludacris)", artist: "Usher", year: 2004 },
  { id: "6nTiIhLmQ3FWhvrGafw2zj", title: "American Idiot", artist: "Green Day", year: 2004 },
  { id: "7d8GetOsjbxYnlo6Y9e5Kw", title: "Mr. Brightside", artist: "The Killers", year: 2004 },
  { id: "1SKPmfSYaPsETbRHaiA18G", title: "Somewhere Only We Know", artist: "Keane", year: 2004 },
  { id: "7oK9VyNzrYvRFo7nQEYkWN", title: "Mr. Brightside", artist: "The Killers", year: 2004 },
  { id: "3ibKnFDaa3GhpPGlOUj7ff", title: "Let Me Love You", artist: "Mario", year: 2004 },
  { id: "68vgtRHr7iZHpzGpon6Jlo", title: "My Boo", artist: "Usher", year: 2004 },
  { id: "1D1nixOVWOxvNfWi0UD7VX", title: "Unwritten", artist: "Natasha Bedingfield", year: 2004 },
  { id: "3ZffCQKLFLUvYM59XKLbVm", title: "Wake Me up When September Ends", artist: "Green Day", year: 2004 },
  { id: "61mWefnWQOLf90gepjOCb3", title: "Duality", artist: "Slipknot", year: 2004 },
  { id: "6jEZLz3YpnEBRpVkv35AmP", title: "Gasolina", artist: "Daddy Yankee", year: 2004 },
  { id: "7LVHVU3tWfcxj5aiPFEW4Q", title: "Fix You", artist: "Coldplay", year: 2005 },
  { id: "4RCWB3V8V0dignt99LZ8vH", title: "Hey There Delilah", artist: "Plain White T's", year: 2005 },
  { id: "3ZFTkvIE7kyPt6Nu3PEa7V", title: "Hips Don't Lie (feat. Wyclef Jean)", artist: "Shakira", year: 2005 },
  { id: "0d28khcov6AiegSCpG5TuT", title: "Feel Good Inc.", artist: "Gorillaz", year: 2005 },
  { id: "5Z01UMMf7V1o0MzF86s6WJ", title: "Lose Yourself - From 8 Mile Soundtrack", artist: "Eminem", year: 2005 },
  { id: "0mUyMawtxj1CJ76kn9gIZK", title: "Bad Day", artist: "Daniel Powter", year: 2005 },
  { id: "0vg4WnUWvze6pBOJDTq99k", title: "You're Beautiful", artist: "James Blunt", year: 2005 },
  { id: "4nva9EpKntUTs6CRSGBCn9", title: "Just A Lil Bit", artist: "50 Cent", year: 2005 },
  { id: "0EYOdF5FCkgOJJla8DI2Md", title: "B.Y.O.B.", artist: "System Of A Down", year: 2005 },
  { id: "2iXdwVdzA0KrI2Q0iZNJbX", title: "Better Together", artist: "Jack Johnson", year: 2005 },
  { id: "2aibwv5hGXSgw7Yru8IYTO", title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers", year: 2006 },
  { id: "5wQnmLuC1W7ATsArWACrgW", title: "Welcome to the Black Parade", artist: "My Chemical Romance", year: 2006 },
  { id: "11bD1JtSjlIgKgZG2134DZ", title: "Chasing Cars", artist: "Snow Patrol", year: 2006 },
  { id: "7j31rVgGX9Q2blT92VBEA0", title: "Teenagers", artist: "My Chemical Romance", year: 2006 },
  { id: "6brl7bwOHmGFkNw3MBqssT", title: "So Sick", artist: "Ne-Yo", year: 2006 },
  { id: "10Nmj3JCNoMeBQ87uw5j8k", title: "Dani California", artist: "Red Hot Chili Peppers", year: 2006 },
  { id: "1vxw6aYJls2oq3gW0DujAo", title: "Crazy", artist: "Gnarls Barkley", year: 2006 },
  { id: "70wYA8oYHoMzhRRkARoMhU", title: "When You Were Young", artist: "The Killers", year: 2006 },
  { id: "2nGFzvICaeEWjIrBrL2RAx", title: "Put Your Records On", artist: "Corinne Bailey Rae", year: 2006 },
  { id: "3Q4WeJmzxuDpzMu9QjQqbM", title: "Big Girls Don't Cry (Personal)", artist: "Fergie", year: 2006 },
  { id: "5imShWWzwqfAJ9gXFpGAQh", title: "Waiting On the World to Change", artist: "John Mayer", year: 2006 },
  { id: "6IwKcFdiRQZOWeYNhUiWIv", title: "No One", artist: "Alicia Keys", year: 2007 },
  { id: "7wZUrN8oemZfsEd1CGkbXE", title: "Bleeding Love", artist: "Leona Lewis", year: 2007 },
  { id: "1hGy2eLcmC8eKx7qr1tOqx", title: "Beautiful Girls", artist: "Sean Kingston", year: 2007 },
  { id: "3FtYbEfBqAlGO46NUDQSAt", title: "Electric Feel", artist: "MGMT", year: 2007 },
  { id: "3Zwu2K0Qa5sT6teCCHPShP", title: "Thnks fr th Mmrs", artist: "Fall Out Boy", year: 2007 },
  { id: "1jJci4qxiYcOHhQR247rEU", title: "Kids", artist: "MGMT", year: 2007 },
  { id: "2aIdVb8v9KTpEZnftkz2mD", title: "Buy U a Drank (Shawty Snappin')", artist: "T-Pain", year: 2007 },
  { id: "66TRwr5uJwPt15mfFkzhbi", title: "Crank That (Soulja Boy)", artist: "Soulja Boy", year: 2007 },
  { id: "7x8dCjCr0x6x2lXKujYD34", title: "The Pretender", artist: "Foo Fighters", year: 2007 },
  { id: "4E6cwWJWZw2zWf7VFbH7wf", title: "Love Song", artist: "Sara Bareilles", year: 2007 },
  { id: "1EzrEOXmMH3G43AXT1y7pA", title: "I'm Yours", artist: "Jason Mraz", year: 2008 },
  { id: "49FYlytm3dAAraYgpoJZux", title: "Umbrella", artist: "Rihanna", year: 2008 },
  { id: "0CAfXk7DXMnon4gLudAp7J", title: "Low (feat. T-Pain)", artist: "Flo Rida", year: 2008 },
  { id: "0ntQJM78wzOLVeCUAW7Y45", title: "Sex on Fire", artist: "Kings of Leon", year: 2008 },
  { id: "1mea3bSkSGXuIRvnydlB5b", title: "Viva La Vida", artist: "Coldplay", year: 2008 },
  { id: "4JehYebiI9JE8sR8MisGVb", title: "Halo", artist: "Beyoncé", year: 2008 },
  { id: "6TfBA04WJ3X1d1wXhaCFVT", title: "You're Gonna Go Far, Kid", artist: "The Offspring", year: 2008 },
  { id: "1QV6tiMFM6fSOKOGLMHYYg", title: "Poker Face", artist: "Lady Gaga", year: 2008 },
  { id: "0ByMNEPAPpOR5H69DVrTNy", title: "Don't Stop The Music", artist: "Rihanna", year: 2008 },
  { id: "5VGlqQANWDKJFl0MBG3sg2", title: "Use Somebody", artist: "Kings of Leon", year: 2008 },
  { id: "4dGJf1SER1T6ooX46vwzRB", title: "Chicken Fried", artist: "Zac Brown Band", year: 2008 },
  { id: "1IAzD1muglOxOcPbUHs70R", title: "Whatever You Like", artist: "T.I.", year: 2008 },
  { id: "3E7dfMvvCLUddWissuqMwr", title: "Party In The U.S.A.", artist: "Miley Cyrus", year: 2009 },
  { id: "0SiywuOBRcynK0uKGWdCnn", title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
  { id: "3DamFFqW32WihKkTVlwTYQ", title: "Fireflies", artist: "Owl City", year: 2009 },
  { id: "7LP4Es66zdY7CyjepqmvAg", title: "Down", artist: "Jay Sean", year: 2009 },
  { id: "1NhPKVLsHhFUHIOZ32QnS2", title: "Secrets", artist: "OneRepublic", year: 2009 },
  { id: "64yrDBpcdwEdNY9loyEGbX", title: "21 Guns", artist: "Green Day", year: 2009 },
  { id: "4VqPOruhp5EdPBeR92t6lQ", title: "Uprising", artist: "Muse", year: 2009 },
  { id: "2UREu1Y8CO4jXkbvqAtP7g", title: "Monster", artist: "Skillet", year: 2009 },
  { id: "4IoYz8XqqdowINzfRrFnhi", title: "You Found Me", artist: "The Fray", year: 2009 },
  { id: "7uUUtCQYzbE917JnobCtDy", title: "היא רק רוצה לרקוד", artist: "עומר אדם", year: 2011 },
  { id: "4cZd8TSEowGRcDsmCvJEjU", title: "אוהבת אותי אמיתי", artist: "עומר אדם", year: 2012 },
  { id: "26o6KYVdmCmh7AY0nhBoKj", title: "תל אביב", artist: "עומר אדם", year: 2013 },
  { id: "7zsT5Dd6rLo8AOrN4Bj4Hl", title: "הלב שלי", artist: "עומר אדם", year: 2014 },
  { id: "0qH6stYoiSWErrzIvkiN1W", title: "שני משוגעים", artist: "עומר אדם", year: 2015 },
  { id: "5qbezFG8xCtoyUfOcjHUXv", title: "אני", artist: "עומר אדם", year: 2015 },
  { id: "4pQo5w8RjtfTRZB2QSxs8e", title: "מלכת השושנים", artist: "עדן בן זקן", year: 2015 },
  { id: "4zXfQYhcSboWEOAwIQST9N", title: "רק שלך", artist: "עומר אדם", year: 2016 },
  { id: "6GCoKavQd5wOqScl5wVXOp", title: "מועבט", artist: "עדן בן זקן", year: 2016 },
  { id: "5ppuL7dOIhd7td0YCJJuwf", title: "טקילה", artist: "עומר אדם", year: 2016 },
  { id: "6kVmhOoBlMEH3WdxrLhjFB", title: "הפשע המושלם", artist: "עדן בן זקן", year: 2016 },
  { id: "4dELL8S6XVMibwBkjJACF1", title: "לילות וקללות", artist: "עומר אדם", year: 2017 },
  { id: "6YQpTZk61Ku0hyutsVLpPe", title: "חיפשתי אותו בנרות", artist: "עדן בן זקן", year: 2017 },
  { id: "1Jx6aZyJR985kw8CWUZ15O", title: "צמוד צמוד", artist: "עומר אדם", year: 2017 },
  { id: "5HhVbTC6HGflJs0I2LHHxf", title: "רציתי", artist: "עדן בן זקן", year: 2017 },
  { id: "4TnjEaWOeW0eKTKIEvJyCa", title: "Falling", artist: "Trevor Daniel", year: 2018 },
  { id: "285pBltuF7vW8TeWk8hdRR", title: "Lucid Dreams", artist: "Juice WRLD", year: 2018 },
  { id: "2dpaYNEQHiRxtZbfNsse99", title: "Happier", artist: "Marshmello", year: 2018 },
  { id: "0u2P5u6lvoDfwTYjAADbn4", title: "lovely (with Khalid)", artist: "Billie Eilish", year: 2018 },
  { id: "3KkXRkHbMCARz0aVfEt68P", title: "Sunflower - Spider-Man: Into the Spider-Verse", artist: "Post Malone", year: 2018 },
  { id: "5p7ujcrUXASCNwRaWNHR1C", title: "Without Me", artist: "Halsey", year: 2018 },
  { id: "7n6elf6gl4POlFO2LlyIMy", title: "בסיבוב הבא", artist: "עדן בן זקן", year: 2018 },
  { id: "7ibWPuw6aT2Vb0hoDUXGHd", title: "יעשו לנו כבוד", artist: "עומר אדם", year: 2018 },
  { id: "4JPoUegxFjxtUgHUcLzoYN", title: "פילטרים יפים", artist: "עדן בן זקן", year: 2018 },
  { id: "2XU0oxnq2qxCpomAAuJY8K", title: "Dance Monkey", artist: "Tones and I", year: 2019 },
  { id: "696DnlkuDOXcMAnKlTgXXK", title: "ROXANNE", artist: "Arizona Zervas", year: 2019 },
  { id: "7k4t7uLgtOxPwTpFmtJNTY", title: "Tusa", artist: "KAROL G", year: 2019 },
  { id: "2b8fOow8UzyDFAE27YhOZM", title: "Memories", artist: "Maroon 5", year: 2019 },
  { id: "0sf12qNH5qcw8qpgymFOqD", title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { id: "21jGcNKet2qwijlDFuPiPb", title: "Circles", artist: "Post Malone", year: 2019 },
  { id: "0nbXyq5TXYPCO7pr3N8S4I", title: "The Box", artist: "Roddy Ricch", year: 2019 },
  { id: "3ZCTVFBt2Brf31RLEnCkWJ", title: "everything i wanted", artist: "Billie Eilish", year: 2019 },
  { id: "6WrI0LAC5M1Rw2MnX2ZvEg", title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
  { id: "6cy3ki60hLwimwIje7tALf", title: "RITMO (Bad Boys For Life)", artist: "The Black Eyed Peas", year: 2019 },
  { id: "2Fxmhks0bxGSBdJ92vM42m", title: "bad guy", artist: "Billie Eilish", year: 2019 },
  { id: "2tnVG71enUj33Ic2nFN6kZ", title: "Ride It", artist: "Regard", year: 2019 },
  { id: "7qEHsqek33rTcFNT9PFqLf", title: "Someone You Loved", artist: "Lewis Capaldi", year: 2019 },
  { id: "3eekarcy7kvN4yt5ZFzltW", title: "HIGHEST IN THE ROOM", artist: "Travis Scott", year: 2019 },
  { id: "7aiClxsDWFRQ0Kzk5KI5ku", title: "hot girl bummer", artist: "blackbear", year: 2019 },
  { id: "3yOlyBJuViE2YSGn3nVE1K", title: "My Oh My (feat. DaBaby)", artist: "Camila Cabello", year: 2019 },
  { id: "2ksOAxtIxY8yElEWw8RhgK", title: "China", artist: "Anuel AA", year: 2019 },
  { id: "0TK2YIli7K1leLovkQiNik", title: "Señorita", artist: "Shawn Mendes", year: 2019 },
  { id: "57vxBYXtHMk6H1aD29V7PU", title: "Heartless", artist: "The Weeknd", year: 2019 },
  { id: "1HfMVBKM75vxSfsQ5VefZ5", title: "Lose You To Love Me", artist: "Selena Gomez", year: 2019 },
  { id: "6Ozh9Ok6h4Oi1wUSLtBseN", title: "BOP", artist: "DaBaby", year: 2019 },
  { id: "5DxXgozhkPLgrbKFY91w0c", title: "Vete", artist: "Bad Bunny", year: 2019 },
  { id: "6Gg1gjgKi2AK4e0qzsR7sd", title: "Bandit (with YoungBoy Never Broke Again)", artist: "Juice WRLD", year: 2019 },
  { id: "5ZULALImTm80tzUbYQYM9d", title: "Dance Monkey", artist: "Tones and I", year: 2019 },
  { id: "6mAN61JH0dzyZpWslS11jy", title: "Fantasias", artist: "Rauw Alejandro", year: 2019 },
  { id: "3VyjsVV24RmBIbWJAeUJNu", title: "No Idea", artist: "Don Toliver", year: 2019 },
  { id: "7CHi4DtfK4heMlQaudCuHK", title: "Lose Control", artist: "MEDUZA", year: 2019 },
  { id: "0fea68AdmYNygeTGI4RC18", title: "LA CANCIÓN", artist: "J Balvin", year: 2019 },
  { id: "1M4qEo4HE3PRaCOM7EXNJq", title: "Adore You", artist: "Harry Styles", year: 2019 },
  { id: "2wrJq5XKLnmhRXHIAf9xBa", title: "10,000 Hours (with Justin Bieber)", artist: "Dan + Shay", year: 2019 },
  { id: "6b2RcmUt1g9N9mQ3CbjX2Y", title: "How Do You Sleep?", artist: "Sam Smith", year: 2019 },
  { id: "4vUmTMuQqjdnvlZmAH61Qk", title: "South of the Border (feat. Camila Cabello & Cardi B)", artist: "Ed Sheeran", year: 2019 },
  { id: "51Fjme0JiitpyXKuyQiCDo", title: "Lalala", artist: "Y2K", year: 2019 },
  { id: "6LcauUZjF1eXQrgqMUecHX", title: "Ayy Macarena", artist: "Tyga", year: 2019 },
  { id: "2Ec33AVlkTTq8BHFgBTdQs", title: "Futsal Shuffle 2020", artist: "Lil Uzi Vert", year: 2019 },
  { id: "5stPVcRqb4qixbafP9e8lt", title: "Hola - Remix", artist: "Dalex", year: 2019 },
  { id: "6RyaV7owmVU6fzEPE17sF1", title: "Que Tire Pa Lante", artist: "Daddy Yankee", year: 2019 },
  { id: "3jbT1Y5MoPwEIpZndDDwVq", title: "Adicto (with Anuel AA & Ozuna)", artist: "Tainy", year: 2019 },
  { id: "7ce20yLkzuXXLUhzIDoZih", title: "Before You Go", artist: "Lewis Capaldi", year: 2019 },
  { id: "1iQDltZqI7BXnHrFy4Qo1k", title: "Trampoline (with ZAYN)", artist: "SHAED", year: 2019 },
  { id: "1lOe9qE0vR9zwWQAOk6CoO", title: "Ransom", artist: "Lil Tecca", year: 2019 },
  { id: "2TH65lNHgvLxCKXM3apjxI", title: "Callaita", artist: "Bad Bunny", year: 2019 },
  { id: "2YpeDb67231RjR0MgVLzsG", title: "Old Town Road - Remix", artist: "Lil Nas X", year: 2019 },
  { id: "1e9oZCCiX42nJl0AcqriVo", title: "Watermelon Sugar", artist: "Harry Styles", year: 2019 },
  { id: "6ocbgoVGwYJhOv1GgI9NsF", title: "7 rings", artist: "Ariana Grande", year: 2019 },
  { id: "3HVWdVOQ0ZA45FuZGSfvns", title: "I Don't Care (with Justin Bieber)", artist: "Ed Sheeran", year: 2019 },
  { id: "1iSqfoUFnQwV0QW1EfUit8", title: "Suicidal", artist: "YNW Melly", year: 2019 },
  { id: "3QzAOrNlsabgbMwlZt7TAY", title: "Ballin' (with Roddy Ricch)", artist: "Mustard", year: 2019 },
  { id: "7sQKy5vlPQllr0k9IjYJv3", title: "Sigues Con El", artist: "Dimelo Flow", year: 2019 },
  { id: "0t3ZvGKlmYmVsDzBJAXK8C", title: "Goodbyes (feat. Young Thug)", artist: "Post Malone", year: 2019 },
  { id: "2pWOMNQJW3g2zmGjP0Vkb0", title: "Whine Up", artist: "Nicky Jam", year: 2019 },
  { id: "2W4yABdLc4Jnds67Poi5Nl", title: "Yellow Hearts", artist: "Ant Saunders", year: 2019 },
  { id: "07Oz5StQ7GRoygNLaXs2pd", title: "Good as Hell (feat. Ariana Grande) - Remix", artist: "Lizzo", year: 2019 },
  { id: "4evmHXcjt3bTUHD1cvny97", title: "Beautiful People (feat. Khalid)", artist: "Ed Sheeran", year: 2019 },
  { id: "5DqdesEfbRyOlSS3Tf6c29", title: "It's You", artist: "Ali Gatie", year: 2019 },
  { id: "7h0d2h0fUmzbs7zeFigJPn", title: "HIGHEST IN THE ROOM (feat. ROSALÍA & Lil Baby) - REMIX", artist: "Travis Scott", year: 2019 },
  { id: "37zdqI4r1gswIzczSBkRon", title: "Aventura", artist: "Lunay", year: 2019 },
  { id: "24Yi9hE78yPEbZ4kxyoXAI", title: "Roses - Imanbek Remix", artist: "SAINt JHN", year: 2019 },
  { id: "59s0s39NFWScuHDbHytI14", title: "Indeciso", artist: "Reik", year: 2019 },
  { id: "2rc7BkzO8qepMFAxHtOrXc", title: "Blanco", artist: "J Balvin", year: 2019 },
  { id: "6v3KW9xbzN5yKLt9YKDYA2", title: "Señorita", artist: "Shawn Mendes", year: 2019 },
  { id: "6osaMSJh9NguagEDQcZaKx", title: "Loco Contigo (feat. J. Balvin & Tyga)", artist: "DJ Snake", year: 2019 },
  { id: "6Y4PDQv4XjYjHLeLmvyOt0", title: "Si Te Vas", artist: "Sech", year: 2019 },
  { id: "7BlBVFwvbWvcwNcUarQmjk", title: "Yo x Ti, Tu x Mi", artist: "ROSALÍA", year: 2019 },
  { id: "5a6pdCHlWS2ekOOQ70QnAr", title: "July", artist: "Noah Cyrus", year: 2019 },
  { id: "2kJwzbxV2ppxnQoYw4GLBZ", title: "If The World Was Ending (feat. Julia Michaels)", artist: "JP Saxe", year: 2019 },
  { id: "3jjujdWJ72nww5eGnfs2E7", title: "Adore You", artist: "Harry Styles", year: 2019 },
  { id: "6kls8cSlUyHW2BUOkDJIZE", title: "Hate Me (with Juice WRLD)", artist: "Ellie Goulding", year: 2019 },
  { id: "598yNsG1JFrGd4n2kMoz7F", title: "Woah", artist: "Lil Baby", year: 2019 },
  { id: "0fySG6A6qLE8IvDpayb5bM", title: "VIBEZ", artist: "DaBaby", year: 2019 },
  { id: "5ry2OE6R2zPQFDO85XkgRb", title: "Money In The Grave (Drake ft. Rick Ross)", artist: "Drake", year: 2019 },
  { id: "6U0FIYXCQ3TGrk4tFpLrEA", title: "SUGAR", artist: "BROCKHAMPTON", year: 2019 },
  { id: "1hTth4TFnHWYWiXglQ6bN2", title: "רחוק מכולם", artist: "עומר אדם", year: 2019 },
  { id: "5L9qCjY83hVP24RIo3rFjZ", title: "קוקוריקו", artist: "עדן בן זקן", year: 2019 },
  { id: "0SMDtYt5HghaTMFc61nCnP", title: "ואיך שלא", artist: "עומר אדם", year: 2019 },
  { id: "7ea31KGrIuCRvHF31ir6GD", title: "לזאת שניצחה", artist: "עדן בן זקן", year: 2019 },
  { id: "41L3O37CECZt3N7ziG2z7l", title: "Yummy", artist: "Justin Bieber", year: 2020 },
  { id: "5yY9lUy8nbvjM1Uyo1Uqoc", title: "Life Is Good (feat. Drake)", artist: "Future", year: 2020 },
  { id: "7HMmFQsKsljwTw8bS7lu19", title: "Rare", artist: "Selena Gomez", year: 2020 },
  { id: "3ClBKQkKoaUQ6UOhe2xlJK", title: "Good News", artist: "Mac Miller", year: 2020 },
  { id: "2usxQITOSDqvkYiI0oIwao", title: "You should be sad", artist: "Halsey", year: 2020 },
  { id: "4l0Mvzj72xxOpRrp6h8nHi", title: "Lose You To Love Me", artist: "Selena Gomez", year: 2020 },
  { id: "1ToprX3cpBiXoAe5eNSk74", title: "Eleven", artist: "Khalid", year: 2020 },
  { id: "3mQ6SLdxxaL52Yte7KF2Ks", title: "Morado", artist: "J Balvin", year: 2020 },
  { id: "4VgYtXCVJ7IbWAZ5ryfvEQ", title: "Muévelo", artist: "Nicky Jam", year: 2020 },
  { id: "2u3EyuCqqV31woqGvO9LBz", title: "Sum 2 Prove", artist: "Lil Baby", year: 2020 },
  { id: "11OwAR3GlBj9E35Cznf7Lj", title: "Vulnerable", artist: "Selena Gomez", year: 2020 },
  { id: "7FIWs0pqAYbP91WWM0vlTQ", title: "Godzilla (feat. Juice WRLD)", artist: "Eminem", year: 2020 },
  { id: "7GCVboEDzfL3NKp1NrAgHR", title: "Wrong Direction", artist: "Hailee Steinfeld", year: 2020 },
  { id: "4Hqh0dS4x07zuRw6eBTO7p", title: "20/20", artist: "Lil Tjay", year: 2020 },
  { id: "70zg99pT51vB4wlMS7e4q7", title: "La Playa - Remix", artist: "Myke Towers", year: 2020 },
  { id: "5Xhqh4lwJPtMUTsdBztN1a", title: "Me Gusta", artist: "Shakira", year: 2020 },
  { id: "5sK3o66yupTNIK6gWgzGjf", title: "Dance Again", artist: "Selena Gomez", year: 2020 },
  { id: "3vUc9WQpoca15404jNdzf9", title: "Changes", artist: "Lauv", year: 2020 },
  { id: "0PQsrLxPbOBBwwmXCnGvcF", title: "Diamonds (with Normani)", artist: "Megan Thee Stallion", year: 2020 },
  { id: "36J10AwMabBYxgNrV2S8gd", title: "6AM.........", artist: "Dardan", year: 2020 },
  { id: "5NYzvVxuyXiHSqn7PojgKC", title: "Ich hol dich ab", artist: "Jamule", year: 2020 },
  { id: "0VSzREd1OjEWJ9tXoFHRQH", title: "Those Kinda Nights (feat. Ed Sheeran)", artist: "Eminem", year: 2020 },
  { id: "5SiZJoLXp3WOl3J4C8IK0d", title: "Darkness", artist: "Eminem", year: 2020 },
  { id: "61ZM92T2zaXIVsqncThQzC", title: "In Your Eyes (feat. Alida)", artist: "Robin Schulz", year: 2020 },
  { id: "4Eefey3uN90Abhbr47zKmC", title: "WINTER FLOWER(Feat.RM)", artist: "Younha", year: 2020 },
  { id: "4wNIkl5XGiAACjFBlDWuSd", title: "What A Man Gotta Do", artist: "Jonas Brothers", year: 2020 },
  { id: "0rsRJOlDJxfNPNTEALa2t3", title: "Rare", artist: "Selena Gomez", year: 2020 },
  { id: "3R8CyhJfVjvgIROd5RSGhQ", title: "I Can See", artist: "Mac Miller", year: 2020 },
  { id: "3yD2LWeCCFu7ybBO3lwbXM", title: "U Played (feat. Lil Baby)", artist: "Moneybagg Yo", year: 2020 },
  { id: "1DWZUa5Mzf2BwzpHtgbHPY", title: "Good News", artist: "Mac Miller", year: 2020 },
  { id: "2eAtC4umRoDcvRcsyFzGL9", title: "Benzo", artist: "Elias", year: 2020 },
  { id: "3FGiFUJRRp5RGikVrs6kig", title: "Underdog", artist: "Alicia Keys", year: 2020 },
  { id: "3IdPtyJHB1WVPM4eCiCAKM", title: "Answer", artist: "ATEEZ", year: 2020 },
  { id: "1aQqtnz30d2vAG54XFNpu0", title: "The Story", artist: "Conan Gray", year: 2020 },
  { id: "2Yv2mHzr5AQavVdwQjEokV", title: "Hand Me Downs", artist: "Mac Miller", year: 2020 },
  { id: "0W9E3s2G4szLUwXsE17x5E", title: "Beach Ballin' (feat. blackbear)", artist: "Yung Pinch", year: 2020 },
  { id: "4q4c1LAerpInH9yUanIIBv", title: "Es geht voran", artist: "RAF Camora", year: 2020 },
  { id: "3Qa944OTMZkg8DHjET8JQv", title: "Woods", artist: "Mac Miller", year: 2020 },
  { id: "3DjInVTE03icrWsq2UZV9n", title: "Recuerdo", artist: "TINI", year: 2020 },
  { id: "17XU1PTSv4OfcBUE8rNYWm", title: "Kiss Somebody", artist: "Julie Bergan", year: 2020 },
  { id: "0YoquWDxpwAq8jFPj3K8wp", title: "Original (from Dolittle)", artist: "Sia", year: 2020 },
  { id: "1lO9CZo6eDrOy0S7khgryG", title: "No Regrets (feat. Don Toliver)", artist: "Eminem", year: 2020 },
  { id: "1hoLUVBx0ixX3kn0EX0P5n", title: "Kein Wort", artist: "Juju", year: 2020 },
  { id: "6eEYGGFfFbtKHCgJM4uh9v", title: "Ordinary Man (feat. Elton John)", artist: "Ozzy Osbourne", year: 2020 },
  { id: "5fXslGZPI5Cco6PKHzlSL3", title: "Illegal Weapon 2.0 (From Street Dancer 3D)", artist: "Jasmine Sandlas", year: 2020 },
  { id: "0EdgK7ASb4kfRkW8pVMN02", title: "2 Hearts (feat. Gia Koka)", artist: "Sam Feldt", year: 2020 },
  { id: "7qeWNGBqqagdwf4KnjRzGZ", title: "U Played (feat. Lil Baby)", artist: "Moneybagg Yo", year: 2020 },
  { id: "78XK5PDIKWiDKcgiLl1x0o", title: "Still Disappointed", artist: "Stormzy", year: 2020 },
  { id: "4qOesAYiMiMFiZrn2wfkl6", title: "Big Drip", artist: "Ufo361", year: 2020 },
  { id: "1y4uzhemSbfya50s7D2Fr3", title: "STREIT MIT DEM MOND", artist: "Kianush", year: 2020 },
  { id: "2Mfv5HaqnI18Q9JRv9hqnn", title: "Still Learning", artist: "Halsey", year: 2020 },
  { id: "7oIAqDzsqgVpUaMXuultdC", title: "Happy", artist: "Oh Wonder", year: 2020 },
  { id: "2wBB2KKqtuK1fcxAiqbCSZ", title: "Hella Neck", artist: "Carnage", year: 2020 },
  { id: "6HPRxfAFmvHZqQHtB1OPPu", title: "Bad Vibe (feat. A Boogie Wit da Hoodie & 2 Chainz)", artist: "Quando Rondo", year: 2020 },
  { id: "0Pqix0NTfbuROfPbaZbBgp", title: "Protect Da Brand (feat. DaBaby)", artist: "Moneybagg Yo", year: 2020 },
  { id: "10UipNaUa43uGsMnBOcCOK", title: "Nur ein Dieb", artist: "Veysel", year: 2020 },
  { id: "3oIVK7arAFuUOCGafPLxSC", title: "Better Off Without You (feat. Shift K3Y)", artist: "Becky Hill", year: 2020 },
  { id: "4yJiXq86uM56uIfIZgE440", title: "me & ur ghost", artist: "blackbear", year: 2020 },
  { id: "5jiJXFYMQpBfPr4N1Z46oI", title: "Virgil Discount", artist: "T.R.U.", year: 2020 },
  { id: "1rAmlvvGBRrhJTCiUjMwBN", title: "Gang Gang", artist: "Miami Yacine", year: 2020 },
  { id: "11PKEBCjw8OCK5YUo9vm0H", title: "Full Circle", artist: "Five Finger Death Punch", year: 2020 },
  { id: "3OSFefosO5NYbS2x0GTLDo", title: "EH BABA", artist: "Murda", year: 2020 },
  { id: "3eq83AsxUcnYS9k57MoBbE", title: "Further Up (Na, Na, Na, Na, Na)", artist: "Static & Ben El", year: 2020 },
  { id: "1yaWRS9r2woTNmJpCKd5l9", title: "Two 10s", artist: "Quinn XCII", year: 2020 },
  { id: "1b3nlcP6hogIzYRVK2Ui7K", title: "Wherever You Are", artist: "Kodaline", year: 2020 },
  { id: "2iObjOsy2vpsariW4Y7hQg", title: "Costa Rica", artist: "Bankrol Hayden", year: 2020 },
  { id: "3OUPJPD1OmFd8gL7ztY9v8", title: "Yelo", artist: "C. Tangana", year: 2020 },
  { id: "0ycFQvBTfuo1LCdG0HhszL", title: "Tattoos Together", artist: "Lauv", year: 2020 },
  { id: "5fmXWEFh8vMXzKTHN9ezKV", title: "En Tus Planes", artist: "David Bisbal", year: 2020 },
  { id: "6qQ8a6M6o5mfj9wTdrbSgG", title: "Older", artist: "Shallou", year: 2020 },
  { id: "1Ia95g66IhlAJ3qVI4qI8W", title: "Slow", artist: "SHY Martin", year: 2020 },
  { id: "1CbFX5cBnMVVwBBI4ssF2G", title: "Para, Money, E's", artist: "JIGGO", year: 2020 },
  { id: "1bObrsJGW0UCIGZkvnDqbe", title: "Stop This Flame", artist: "Celeste", year: 2020 },
  { id: "1XFHbzTikXks9CsMq4v8Q3", title: "Not So Bad (feat. Emie)", artist: "Yves V", year: 2020 },
  { id: "44GSjYhBxuuKx0ikN5Dmag", title: "יהיה טוב & מים שקופים", artist: "עומר אדם", year: 2020 },
  { id: "52wQnuYSGb6DofAGQNLMsa", title: "תזיזו", artist: "עדן בן זקן", year: 2020 },
  { id: "18YUiBqnHhzsRr0k1ppP18", title: "תל אביב בלילה", artist: "עדן בן זקן", year: 2020 },
  { id: "0sCN2Vt33MyAmsHpNxR2Kq", title: "חיים מאושרים", artist: "עדן בן זקן", year: 2021 },
  { id: "3pTsE064ZTJ1n8bP3VAm2c", title: "תהום", artist: "עומר אדם", year: 2021 },
  { id: "1BKXM5acD2NHjBaWTCsXFk", title: "מהפכה של שמחה", artist: "עומר אדם", year: 2022 },
  { id: "5liIuoKq6hJZOheB95eTCt", title: "אגרוף", artist: "עדן בן זקן", year: 2022 },
  { id: "5ArZAXZjGqDC95HySnhvN3", title: "חיים שלי", artist: "עדן בן זקן", year: 2022 },
  { id: "5aDaDlIrhFeXUPcBqxGisR", title: "אחרי כל השנים", artist: "עומר אדם", year: 2023 },
  { id: "5gmwl9W6Ym0JMEgkUPtXe6", title: "יאסו", artist: "עדן בן זקן", year: 2023 },
  { id: "4JSUFLR3Uo7FPCfNDRxIrx", title: "ברחובות של תל אביב", artist: "עדן בן זקן", year: 2023 },
  { id: "3U1voPJN8NBSR96Ry0WJiF", title: "מלכת הדור", artist: "עומר אדם", year: 2024 },
  { id: "5Sn3aXG5AWFmd1ij2PTisj", title: "השיר שאת אהבת", artist: "עומר אדם", year: 2024 },
  { id: "6Ma5wr8hndGkkjsk9rgVKS", title: "היא לא יודעת למה", artist: "Peer Tasi", year: 2024 },
  { id: "3Dx920qUWdBswFizsT1PxR", title: "באמת של האמת", artist: "Osher Cohen", year: 2024 },
  { id: "05iw1Zb7Lp5DNUSvDhBRk6", title: "נגנב ממך", artist: "Full Trunk", year: 2024 },
  { id: "4WoKmBYVGyrf7t0SkHhMQ1", title: "אין כבוד", artist: "Osher Cohen", year: 2024 },
  { id: "6Gt2PGz5zL9HnnJo3UvDV4", title: "עולם בשני צבעים", artist: "ששון שאולוב", year: 2024 },
  { id: "6VYbnnpUYShqFn22MERtmP", title: "המבט בעיניך", artist: "Agam Buhbut", year: 2024 },
  { id: "7iepAdmAykL8gh7dYMzpsM", title: "רולקס וקסקט", artist: "עדן בן זקן", year: 2025 },
  { id: "3gdSZLWC594njZXkwWh7lQ", title: "ואן דאם", artist: "Odeya", year: 2025 },
  { id: "6FVNMp4r4cQOcckK5NFB6j", title: "אם את כבר הולכת", artist: "נדב חנציס", year: 2025 },
  { id: "02mgxr6NgCwAVtuLtttDUB", title: "מדאם", artist: "Noam Bettan", year: 2025 },
  { id: "2bzhJBao5xywL3jlXu2S8O", title: "סחרחורות", artist: "Mor", year: 2025 },
  { id: "7nCe56CzvRKGqTIs5k1dYm", title: "עוף מוזר", artist: "Peer Tasi", year: 2025 },
  { id: "3XSSUNQJHy7GTWtSHHITq5", title: "השם ירחם", artist: "Tuna", year: 2025 }
];
