// Yearster Song Database - Auto-generated from verified Spotify data + Hebrew songs
// 300 songs from 1970-2025
// Target: ~50 songs per decade (English + Hebrew)
// Each entry: { id: Spotify Track ID, title, artist, year }

const SONGS = [
  { id: "7iN1s7xHE4ifF5povM6A48", title: "Let It Be - Remastered 2009", artist: "The Beatles", year: 1970 },
  { id: "2LawezPeJhN4AWuSB0GtAU", title: "Have You Ever Seen The Rain", artist: "Creedence Clearwater Revival", year: 1970 },
  { id: "78lgmZwycJ3nzsdgmPPGNx", title: "Immigrant Song - Remaster", artist: "Led Zeppelin", year: 1970 },
  { id: "1jzDzZWeSDBg5fhNc3tczV", title: "Paranoid", artist: "Black Sabbath", year: 1970 },
  { id: "0qdQUeKVyevrbKhAo0ibxS", title: "My Sweet Lord", artist: "George Harrison", year: 1970 },
  { id: "2TVxnKdb3tqe1nhQWwwZCO", title: "Tiny Dancer", artist: "Elton John", year: 1971 },
  { id: "5CQ30WqJwcep0pYcV4AMNc", title: "Stairway to Heaven - Remaster", artist: "Led Zeppelin", year: 1971 },
  { id: "3qiyyUfYe7CRYLucrPmulD", title: "Baba O'Riley", artist: "The Who", year: 1971 },
  { id: "1k1Bqnv2R0uJXQN4u6LKYt", title: "Ain't No Sunshine", artist: "Bill Withers", year: 1971 },
  { id: "14XWXWv5FoCbFzLksawpEe", title: "Riders on the Storm", artist: "The Doors", year: 1971 },
  { id: "3gdewACMIVMEWVbyb8O9sY", title: "Rocket Man (I Think It's Going To Be A Long, Long Time)", artist: "Elton John", year: 1972 },
  { id: "54eZmuggBFJbV7k248bTTt", title: "A Horse with No Name", artist: "America", year: 1972 },
  { id: "7Ar4G7Ci11gpt6sfH9Cgz5", title: "Listen to the Music", artist: "The Doobie Brothers", year: 1972 },
  { id: "2DnJjbjNTV9Nd5NOa1KGba", title: "You're so Vain", artist: "Carly Simon", year: 1972 },
  { id: "5MMnwYs0hIxkENRsbkWJ2G", title: "Smoke On The Water - Remastered 2012", artist: "Deep Purple", year: 1972 },
  { id: "4yugZvBYaoREkJKtbG08Qr", title: "Take It Easy - 2013 Remaster", artist: "Eagles", year: 1972 },
  { id: "5p3JunprHCxClJjOmcLV8G", title: "Walk On the Wild Side", artist: "Lou Reed", year: 1972 },
  { id: "5MxNLUsfh7uzROypsoO5qe", title: "Dream On", artist: "Aerosmith", year: 1973 },
  { id: "6Ac4NVYYl2U73QiTt11ZKd", title: "Hooked on a Feeling", artist: "Blue Swede", year: 1973 },
  { id: "1bp2IO61zbQrbWNmKKxg3f", title: "The Joker", artist: "Steve Miller Band", year: 1973 },
  { id: "70YvYr2hGlS01bKRIho1HM", title: "La Grange - 2005 Remaster", artist: "ZZ Top", year: 1973 },
  { id: "7e89621JPkKaeDSTQ3avtg", title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974 },
  { id: "4u7EnebtmKWzUH433cf5Qv", title: "Bohemian Rhapsody - 2011 Mix", artist: "Queen", year: 1975 },
  { id: "5ihS6UUlyQAfmp48eSkxuQ", title: "Landslide", artist: "Fleetwood Mac", year: 1975 },
  { id: "6mFkJmJqdDVQ1REhVfGgd1", title: "Wish You Were Here", artist: "Pink Floyd", year: 1975 },
  { id: "7tFiyTwD0nx5a1eklYtX2J", title: "Bohemian Rhapsody - 2011 Mix", artist: "Queen", year: 1975 },
  { id: "6KTv0Z8BmVqM7DPxbGzpVC", title: "Rock And Roll All Nite", artist: "KISS", year: 1975 },
  { id: "40riOy7x9W7GXjyGp4pjAv", title: "Hotel California - 2013 Remaster", artist: "Eagles", year: 1976 },
  { id: "1QEEqeFIZktqIpPI4jSVSF", title: "More Than a Feeling", artist: "Boston", year: 1976 },
  { id: "7LRMbd3LEoV5wZJvXT1Lwb", title: "T.N.T.", artist: "AC/DC", year: 1976 },
  { id: "5QTxFnGygVM4jFQiBovmRo", title: "(Don't Fear) The Reaper", artist: "Blue Öyster Cult", year: 1976 },
  { id: "4DMKwE2E2iYDKY01C335Uw", title: "Carry on Wayward Son", artist: "Kansas", year: 1976 },
  { id: "43DeSV93pJPT4lCZaWZ6b1", title: "The Boys Are Back In Town", artist: "Thin Lizzy", year: 1976 },
  { id: "0KMGxYKeUzK9wc5DZCt3HT", title: "If You Leave Me Now", artist: "Chicago", year: 1976 },
  { id: "4pbJqGIASGPr0ZpGpnWkDn", title: "We Will Rock You - Remastered", artist: "Queen", year: 1977 },
  { id: "2RlgNHKcydI9sayD2Df2xp", title: "Mr. Blue Sky", artist: "Electric Light Orchestra", year: 1977 },
  { id: "0ofHAoxe9vBkTCp2UQIavz", title: "Dreams - 2004 Remaster", artist: "Fleetwood Mac", year: 1977 },
  { id: "5e9TFTbltYBg2xThimr0rU", title: "The Chain - 2004 Remaster", artist: "Fleetwood Mac", year: 1977 },
  { id: "6zeE5tKyr8Nu882DQhhSQI", title: "Dust in the Wind", artist: "Kansas", year: 1977 },
  { id: "1lCRw5FEZ1gPDNPzy1K4zW", title: "We Are The Champions - Remastered 2011", artist: "Queen", year: 1977 },
  { id: "7Jh1bpe76CNTCgdgAdBw4Z", title: "Heroes - 2017 Remaster", artist: "David Bowie", year: 1977 },
  { id: "6XUHsYE38CEbYunT983O9G", title: "Give A Little Bit", artist: "Supertramp", year: 1977 },
  { id: "5T8EDUDqKcs6OSOwEsfqG7", title: "Don't Stop Me Now - 2011 Mix", artist: "Queen", year: 1978 },
  { id: "3EYOJ48Et32uATr9ZmLnAo", title: "Roxanne", artist: "The Police", year: 1978 },
  { id: "4aVuWgvD0X63hcOCnZtNFA", title: "Hold the Line", artist: "TOTO", year: 1978 },
  { id: "7hQJA50XrCWABAu5v6QZ4i", title: "Don't Stop Me Now - 2011 Mix", artist: "Queen", year: 1978 },
  { id: "2zYzyRzz6pRmhPzyfMEC8s", title: "Highway to Hell", artist: "AC/DC", year: 1979 },
  { id: "07q0QVgO56EorrSGHC48y3", title: "I Was Made For Lovin' You", artist: "KISS", year: 1979 },
  { id: "4gMgiXfqyzZLMhsksGmbQV", title: "Another Brick in the Wall, Pt. 2", artist: "Pink Floyd", year: 1979 },
  { id: "5HNCy40Ni5BZJFw1TKzRsC", title: "Comfortably Numb", artist: "Pink Floyd", year: 1979 },
  { id: "08mG3Y1vljYA6bvDt4Wqkj", title: "Back In Black", artist: "AC/DC", year: 1980 },
  { id: "5vdp5UmvTsnMEMESIF2Ym7", title: "Another One Bites The Dust - Remastered 2011", artist: "Queen", year: 1980 },
  { id: "2SiXAy7TuUkycRVbbWDEpo", title: "You Shook Me All Night Long", artist: "AC/DC", year: 1980 },
  { id: "2b9lp5A6CqSzwOrBfAFhof", title: "Crazy Train", artist: "Ozzy Osbourne", year: 1980 },
  { id: "4o6BgsqLIBViaGVbx5rbRk", title: "You Make My Dreams", artist: "Daryl Hall & John Oates", year: 1980 },
  { id: "6xdLJrVj4vIXwhuG8TMopk", title: "Crazy Little Thing Called Love - Remastered 2011", artist: "Queen", year: 1980 },
  { id: "57JVGBtBLCfHw2muk5416J", title: "Another One Bites The Dust - Remastered 2011", artist: "Queen", year: 1980 },
  { id: "4bHsxqR3GMrXTxEPLuK5ue", title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
  { id: "7HKez549fwJQDzx3zLjHKC", title: "Start Me Up - Remastered", artist: "The Rolling Stones", year: 1981 },
  { id: "18AXbzPzBS8Y3AkgSxzJPb", title: "In The Air Tonight - 2015 Remastered", artist: "Phil Collins", year: 1981 },
  { id: "3L7RtEcu1Hw3OXrpnthngx", title: "Don't You Want Me", artist: "The Human League", year: 1981 },
  { id: "0cGG2EouYCEEC3xfa0tDFV", title: "Tainted Love", artist: "Soft Cell", year: 1981 },
  { id: "2374M0fQpWi3dLnB54qaLX", title: "Africa", artist: "TOTO", year: 1982 },
  { id: "5ChkMS8OtdzJeqyybCc9R5", title: "Billie Jean", artist: "Michael Jackson", year: 1982 },
  { id: "2fuCquhmrzHpu5xcA1ci9x", title: "Under Pressure - Remastered", artist: "Queen", year: 1982 },
  { id: "39shmbIHICJ2Wxnk1fPSdz", title: "Should I Stay or Should I Go - Remastered", artist: "The Clash", year: 1982 },
  { id: "1OOtq8tRnDM8kG2gqUPjAj", title: "Beat It - Single Version", artist: "Michael Jackson", year: 1982 },
  { id: "1JSTJqkT5qHq8MDJnJbRE1", title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { id: "1TfqLAPs4K3s2rJMoCokcS", title: "Sweet Dreams (Are Made of This) - Remastered", artist: "Eurythmics", year: 1983 },
  { id: "5zA8vzDGqPl2AzZkEYQGKh", title: "Uptown Girl", artist: "Billy Joel", year: 1983 },
  { id: "4y1LsJpmMti1PfRQV9AWWe", title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
  { id: "7N3PAbqfTjSEU1edb2tY8j", title: "Jump - 2015 Remaster", artist: "Van Halen", year: 1984 },
  { id: "1JLn8RhQzHz3qDqsChcmBl", title: "I Want to Know What Love Is - 1999 Remaster", artist: "Foreigner", year: 1984 },
  { id: "4gvea7UlDkAvsJBPZAd4oB", title: "The Boys Of Summer", artist: "Don Henley", year: 1984 },
  { id: "7FwBtcecmlpc1sLySPXeGE", title: "Dancing In the Dark", artist: "Bruce Springsteen", year: 1984 },
  { id: "0dOg1ySSI7NkpAe89Zo0b9", title: "Born in the U.S.A.", artist: "Bruce Springsteen", year: 1984 },
  { id: "2WfaOiMkCvy7F5fcp2zZ8L", title: "Take on Me", artist: "a-ha", year: 1985 },
  { id: "4RvWPyQ5RL0ao9LPZeSouE", title: "Everybody Wants To Rule The World", artist: "Tears For Fears", year: 1985 },
  { id: "2KH16WveTQWT6KOG9Rg6e2", title: "Eye of the Tiger", artist: "Survivor", year: 1985 },
  { id: "3Ud6fFep5ZlXzRWw6Sm8no", title: "Walk Of Life", artist: "Dire Straits", year: 1985 },
  { id: "37ZJ0p5Jm13JPevGcx4SkF", title: "Livin' On A Prayer", artist: "Bon Jovi", year: 1986 },
  { id: "2pnPe4pJtq7689i5ydzvJJ", title: "Run Rudolph Run - Single Version", artist: "Chuck Berry", year: 1986 },
  { id: "3MrRksHupTVEQ7YbA0FsZK", title: "The Final Countdown", artist: "Europe", year: 1986 },
  { id: "0qxYx4F3vm1AOnfux6dDxP", title: "You Can Call Me Al", artist: "Paul Simon", year: 1986 },
  { id: "7o2CTH4ctstm8TNelqjb51", title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { id: "2tUBqZG2AbRi7Q0BIrVrEj", title: "I Wanna Dance with Somebody (Who Loves Me)", artist: "Whitney Houston", year: 1987 },
  { id: "6ADSaE87h8Y3lccZlBJdXH", title: "With Or Without You - Remastered", artist: "U2", year: 1987 },
  { id: "0bVtevEgtDIeRjCJbK3Lmv", title: "Welcome To The Jungle", artist: "Guns N' Roses", year: 1987 },
  { id: "3YBZIN3rekqsKxbJc9FZko", title: "Paradise City", artist: "Guns N' Roses", year: 1987 },
  { id: "1uKjQoh8JZj9ryuYRhpd7E", title: "Ahora Te Puedes Marchar", artist: "Luis Miguel", year: 1987 },
  { id: "6wpGqhRvJGNNXwWlPmkMyO", title: "I Still Haven't Found What I'm Looking For", artist: "U2", year: 1987 },
  { id: "0HEmnAUT8PHznIAAmVXqFJ", title: "Faith - Remastered", artist: "George Michael", year: 1987 },
  { id: "0PdM2a6oIjqepoEfcJo0RO", title: "Pour Some Sugar On Me - Remastered 2017", artist: "Def Leppard", year: 1987 },
  { id: "2M9ro2krNb7nr7HSprkEgo", title: "Fast Car", artist: "Tracy Chapman", year: 1988 },
  { id: "78TnMTAFmWUWWCgNXR7D3K", title: "Listen to Your Heart", artist: "Roxette", year: 1988 },
  { id: "6F9yAYUaNbUhdlQyt5uZ3b", title: "La Incondicional", artist: "Luis Miguel", year: 1988 },
  { id: "6mcxQ1Y3uQRU0IHsvdNLH1", title: "Where Is My Mind?", artist: "Pixies", year: 1988 },
  { id: "7GonnnalI2s19OCQO1J7Tf", title: "Kickstart My Heart", artist: "Mötley Crüe", year: 1989 },
  { id: "5tVA6TkbaAH9QMITTQRrNv", title: "Free Fallin'", artist: "Tom Petty", year: 1989 },
  { id: "4LFwNJWoj74Yd71fIr1W8x", title: "Right Here Waiting", artist: "Richard Marx", year: 1989 },
  { id: "57bgtoPSgt236HzfBOd8kj", title: "Thunderstruck", artist: "AC/DC", year: 1990 },
  { id: "3ovjw5HZZv43SxTwApooCM", title: "Wind Of Change", artist: "Scorpions", year: 1990 },
  { id: "2SbsvihBJmgNKZ4qkXFWrp", title: "More Than Words", artist: "Extreme", year: 1990 },
  { id: "38xhBO2AKrJnjdjVnhJES6", title: "This Christmas", artist: "Donny Hathaway", year: 1990 },
  { id: "31AOj9sFz2gM0O3hMARRBx", title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
  { id: "3d9DChrdc6BOeFsbrZ3Is0", title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1991 },
  { id: "1f3yAtsJtY87CTmM8RLnxf", title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { id: "5sICkBXVmaCQk5aISGR3x1", title: "Enter Sandman", artist: "Metallica", year: 1991 },
  { id: "3G69vJMWsX6ZohTykad2AU", title: "One", artist: "U2", year: 1991 },
  { id: "4JiEyzf0Md7KEFFGWDDdCr", title: "Knockin' On Heaven's Door", artist: "Guns N' Roses", year: 1991 },
  { id: "6QewNVIDKdSl8Y3ycuHIei", title: "Even Flow", artist: "Pearl Jam", year: 1991 },
  { id: "1L94M3KIu7QluZe63g64rv", title: "Alive", artist: "Pearl Jam", year: 1991 },
  { id: "5Xak5fmy089t0FYmh3VJiY", title: "Black", artist: "Pearl Jam", year: 1991 },
  { id: "59WN2psjkt1tyaxjspN8fp", title: "Killing In The Name", artist: "Rage Against The Machine", year: 1992 },
  { id: "4QlzkaRHtU8gAdwqjWmO8n", title: "Friday I'm In Love", artist: "The Cure", year: 1992 },
  { id: "2qOm7ukLyHUXWyR4ZWLwxA", title: "It Was A Good Day", artist: "Ice Cube", year: 1992 },
  { id: "6b2oQwSGFkzsMtQruIWm2p", title: "Creep", artist: "Radiohead", year: 1993 },
  { id: "0gEyKnHvgkrkBM6fbeHdwK", title: "Linger", artist: "The Cranberries", year: 1993 },
  { id: "0bYg9bo50gSsH3LtXe2SQn", title: "All I Want for Christmas Is You", artist: "Mariah Carey", year: 1994 },
  { id: "2IZZqH4K02UIYg5EohpNHF", title: "Zombie", artist: "The Cranberries", year: 1994 },
  { id: "6L89mwZXSOwYl76YXfX13s", title: "Basket Case", artist: "Green Day", year: 1994 },
  { id: "5ByAIlEEnxYdvpnezg7HTX", title: "Juicy - 2005 Remaster", artist: "The Notorious B.I.G.", year: 1994 },
  { id: "1Dr1fXbc2IxaK1Mu8P8Khz", title: "When I Come Around", artist: "Green Day", year: 1994 },
  { id: "7lQWRAjyhTpCWFC0jmclT4", title: "Gangsta's Paradise", artist: "Coolio", year: 1995 },
  { id: "5qqabIl2vWzo9ApSC317sa", title: "Wonderwall - Remastered", artist: "Oasis", year: 1995 },
  { id: "1Je1IMUlBXcx1Fz0WE7oPT", title: "Wannabe", artist: "Spice Girls", year: 1996 },
  { id: "3ssX20QT5c3nA9wk78V1LQ", title: "Ambitionz Az A Ridah", artist: "2Pac", year: 1996 },
  { id: "6MdqqkQ8sSC0WB4i8PyRuQ", title: "No Diggity", artist: "Blackstreet", year: 1996 },
  { id: "2xTft6GEZeTyWNpdX94rkf", title: "All Eyez On Me", artist: "2Pac", year: 1996 },
  { id: "57iDDD9N9tTWe75x6qhStw", title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997 },
  { id: "5UWwZ5lm5PKu6eKsHAGxOk", title: "Everlong", artist: "Foo Fighters", year: 1997 },
  { id: "7KwZNVEaqikRSBSpyhXK2j", title: "Hypnotize - 2014 Remaster", artist: "The Notorious B.I.G.", year: 1997 },
  { id: "6ORqU0bHbVCRjXm9AjyHyZ", title: "Good Riddance (Time of Your Life)", artist: "Green Day", year: 1997 },
  { id: "1FTSo4v6BOZH9QxKc3MbVM", title: "Song 2 - 2012 Remaster", artist: "Blur", year: 1997 },
  { id: "6Qyc6fS4DsZjB2mRW9DsQs", title: "Iris", artist: "The Goo Goo Dolls", year: 1998 },
  { id: "2goLsvvODILDzeeiT4dAoR", title: "Believe", artist: "Cher", year: 1998 },
  { id: "4EchqUKQ3qAQuRNKmeIpnf", title: "The Kids Aren't Alright", artist: "The Offspring", year: 1998 },
  { id: "225xvV8r1yKMHErSWivnow", title: "I Don't Want to Miss a Thing - From Armageddon Soundtrack", artist: "Aerosmith", year: 1998 },
  { id: "4jDmJ51x1o9NZB5Nxxc7gY", title: "Careless Whisper", artist: "George Michael", year: 1998 },
  { id: "48UPSzbZjgc449aqz8bxox", title: "Californication", artist: "Red Hot Chili Peppers", year: 1999 },
  { id: "3cfOd4CMv2snFaKAnMdnvK", title: "All Star", artist: "Smash Mouth", year: 1999 },
  { id: "1KGi9sZVMeszgZOWivFpxs", title: "No Scrubs", artist: "TLC", year: 1999 },
  { id: "64BbK9SFKH2jk86U3dGj2P", title: "Otherside", artist: "Red Hot Chili Peppers", year: 1999 },
  { id: "2m1hi0nfMR9vdGC8UcrnwU", title: "All The Small Things", artist: "blink-182", year: 1999 },
  { id: "1G391cbiT3v3Cywg8T7DM1", title: "Scar Tissue", artist: "Red Hot Chili Peppers", year: 1999 },
  { id: "6x4tKaOzfNJpEJHySoiJcs", title: "Mambo No. 5 (a Little Bit of...)", artist: "Lou Bega", year: 1999 },
  { id: "7H6ev70Weq6DdpZyyTmUXk", title: "Say My Name", artist: "Destiny's Child", year: 1999 },
  { id: "3MjUtNVVq3C8Fn0MP3zhXa", title: "...Baby One More Time", artist: "Britney Spears", year: 1999 },
  { id: "503OTo2dSqe7qk76rgsbep", title: "Still D.R.E.", artist: "Dr. Dre", year: 1999 },
  { id: "5prTs2HAw2G4idHZyeFp8o", title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", year: 1999 },
  { id: "60a0Rd6pjrkxjPbaKzXjfq", title: "In the End", artist: "Linkin Park", year: 2000 },
  { id: "3AJwUDP919kvQ9QcozQPxg", title: "Yellow", artist: "Coldplay", year: 2000 },
  { id: "3yfqSUWxFvZELEM4PmlwIR", title: "The Real Slim Shady", artist: "Eminem", year: 2000 },
  { id: "0I3q5fE6wg7LIfHGngUTnV", title: "Ms. Jackson", artist: "OutKast", year: 2000 },
  { id: "6ZOBP3NvffbU4SZcrnt1k6", title: "Kryptonite", artist: "3 Doors Down", year: 2000 },
  { id: "2DlHlPMa4M17kufBvI2lEN", title: "Chop Suey!", artist: "System Of A Down", year: 2001 },
  { id: "5W8YXBz9MTIDyrpYaCg2Ky", title: "Last Resort", artist: "Papa Roach", year: 2001 },
  { id: "0gmbgwZ8iqyMPmXefof8Yf", title: "How You Remind Me", artist: "Nickelback", year: 2001 },
  { id: "0snQkGI5qnAmohLE7jTsTn", title: "Toxicity", artist: "System Of A Down", year: 2001 },
  { id: "2hKdd3qO7cWr2Jo0Bcs0MA", title: "Drops of Jupiter", artist: "Train", year: 2001 },
  { id: "7vFv0yFGMJW3qVXbAd9BK9", title: "Your Body Is a Wonderland", artist: "John Mayer", year: 2001 },
  { id: "75JFxkI2RXiU7L9VXzMkle", title: "The Scientist", artist: "Coldplay", year: 2002 },
  { id: "4xkOaSrkexMciUUogZKVTS", title: "'Till I Collapse", artist: "Eminem", year: 2002 },
  { id: "4llK75pXNWZz6KAho2Gp16", title: "She Will Be Loved - Radio Mix", artist: "Maroon 5", year: 2002 },
  { id: "3ZOEytgrvLwQaqXreDs2Jx", title: "Can't Stop", artist: "Red Hot Chili Peppers", year: 2002 },
  { id: "5xEM5hIgJ1jjgcEBfpkt2F", title: "Complicated", artist: "Avril Lavigne", year: 2002 },
  { id: "0ARK753YaiJbpLUk7z5yIM", title: "Dilemma", artist: "Nelly", year: 2002 },
  { id: "2nLtzopw4rPReszdYBJU6h", title: "Numb", artist: "Linkin Park", year: 2003 },
  { id: "6I9VzXrHxO9rA9A5euc8Ak", title: "Toxic", artist: "Britney Spears", year: 2003 },
  { id: "47wPvRG8FEwbZP22UBgTQr", title: "Seven Nation Army", artist: "The White Stripes", year: 2003 },
  { id: "0COqiPhxzoWICwFCS4eZcp", title: "Bring Me To Life", artist: "Evanescence", year: 2003 },
  { id: "2PpruBYCo4H7WOBJ7Q2EwM", title: "Hey Ya!", artist: "OutKast", year: 2003 },
  { id: "3XVBdLihbNbxUwZosxcGuJ", title: "If I Ain't Got You", artist: "Alicia Keys", year: 2003 },
  { id: "7iL6o9tox1zgHpKUfh9vuC", title: "In Da Club", artist: "50 Cent", year: 2003 },
  { id: "5rb9QrpfcKFHM1EUbSIurX", title: "Yeah! (feat. Lil Jon & Ludacris)", artist: "Usher", year: 2004 },
  { id: "6nTiIhLmQ3FWhvrGafw2zj", title: "American Idiot", artist: "Green Day", year: 2004 },
  { id: "7d8GetOsjbxYnlo6Y9e5Kw", title: "Mr. Brightside", artist: "The Killers", year: 2004 },
  { id: "1SKPmfSYaPsETbRHaiA18G", title: "Somewhere Only We Know", artist: "Keane", year: 2004 },
  { id: "7LVHVU3tWfcxj5aiPFEW4Q", title: "Fix You", artist: "Coldplay", year: 2005 },
  { id: "4RCWB3V8V0dignt99LZ8vH", title: "Hey There Delilah", artist: "Plain White T's", year: 2005 },
  { id: "3ZFTkvIE7kyPt6Nu3PEa7V", title: "Hips Don't Lie (feat. Wyclef Jean)", artist: "Shakira", year: 2005 },
  { id: "0d28khcov6AiegSCpG5TuT", title: "Feel Good Inc.", artist: "Gorillaz", year: 2005 },
  { id: "5Z01UMMf7V1o0MzF86s6WJ", title: "Lose Yourself - From 8 Mile Soundtrack", artist: "Eminem", year: 2005 },
  { id: "2aibwv5hGXSgw7Yru8IYTO", title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers", year: 2006 },
  { id: "5wQnmLuC1W7ATsArWACrgW", title: "Welcome to the Black Parade", artist: "My Chemical Romance", year: 2006 },
  { id: "11bD1JtSjlIgKgZG2134DZ", title: "Chasing Cars", artist: "Snow Patrol", year: 2006 },
  { id: "6IwKcFdiRQZOWeYNhUiWIv", title: "No One", artist: "Alicia Keys", year: 2007 },
  { id: "7wZUrN8oemZfsEd1CGkbXE", title: "Bleeding Love", artist: "Leona Lewis", year: 2007 },
  { id: "1hGy2eLcmC8eKx7qr1tOqx", title: "Beautiful Girls", artist: "Sean Kingston", year: 2007 },
  { id: "3FtYbEfBqAlGO46NUDQSAt", title: "Electric Feel", artist: "MGMT", year: 2007 },
  { id: "1EzrEOXmMH3G43AXT1y7pA", title: "I'm Yours", artist: "Jason Mraz", year: 2008 },
  { id: "49FYlytm3dAAraYgpoJZux", title: "Umbrella", artist: "Rihanna", year: 2008 },
  { id: "0CAfXk7DXMnon4gLudAp7J", title: "Low (feat. T-Pain)", artist: "Flo Rida", year: 2008 },
  { id: "0ntQJM78wzOLVeCUAW7Y45", title: "Sex on Fire", artist: "Kings of Leon", year: 2008 },
  { id: "1mea3bSkSGXuIRvnydlB5b", title: "Viva La Vida", artist: "Coldplay", year: 2008 },
  { id: "4JehYebiI9JE8sR8MisGVb", title: "Halo", artist: "Beyoncé", year: 2008 },
  { id: "6TfBA04WJ3X1d1wXhaCFVT", title: "You're Gonna Go Far, Kid", artist: "The Offspring", year: 2008 },
  { id: "3E7dfMvvCLUddWissuqMwr", title: "Party In The U.S.A.", artist: "Miley Cyrus", year: 2009 },
  { id: "0SiywuOBRcynK0uKGWdCnn", title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
  { id: "3DamFFqW32WihKkTVlwTYQ", title: "Fireflies", artist: "Owl City", year: 2009 },
  { id: "7uUUtCQYzbE917JnobCtDy", title: "היא רק רוצה לרקוד", artist: "עומר אדם", year: 2011 },
  { id: "4cZd8TSEowGRcDsmCvJEjU", title: "אוהבת אותי אמיתי", artist: "עומר אדם", year: 2012 },
  { id: "26o6KYVdmCmh7AY0nhBoKj", title: "תל אביב", artist: "עומר אדם", year: 2013 },
  { id: "7zsT5Dd6rLo8AOrN4Bj4Hl", title: "הלב שלי", artist: "עומר אדם", year: 2014 },
  { id: "0qH6stYoiSWErrzIvkiN1W", title: "שני משוגעים", artist: "עומר אדם", year: 2015 },
  { id: "5qbezFG8xCtoyUfOcjHUXv", title: "אני", artist: "עומר אדם", year: 2015 },
  { id: "4pQo5w8RjtfTRZB2QSxs8e", title: "מלכת השושנים", artist: "עדן בן זקן", year: 2015 },
  { id: "4zXfQYhcSboWEOAwIQST9N", title: "רק שלך", artist: "עומר אדם", year: 2016 },
  { id: "6GCoKavQd5wOqScl5wVXOp", title: "מועבט", artist: "עדן בן זקן", year: 2016 },
  { id: "5ppuL7dOIhd7td0YCJJuwf", title: "טקילה", artist: "עומר אדם", year: 2016 },
  { id: "6kVmhOoBlMEH3WdxrLhjFB", title: "הפשע המושלם", artist: "עדן בן זקן", year: 2016 },
  { id: "4dELL8S6XVMibwBkjJACF1", title: "לילות וקללות", artist: "עומר אדם", year: 2017 },
  { id: "6YQpTZk61Ku0hyutsVLpPe", title: "חיפשתי אותו בנרות", artist: "עדן בן זקן", year: 2017 },
  { id: "1Jx6aZyJR985kw8CWUZ15O", title: "צמוד צמוד", artist: "עומר אדם", year: 2017 },
  { id: "5HhVbTC6HGflJs0I2LHHxf", title: "רציתי", artist: "עדן בן זקן", year: 2017 },
  { id: "4TnjEaWOeW0eKTKIEvJyCa", title: "Falling", artist: "Trevor Daniel", year: 2018 },
  { id: "285pBltuF7vW8TeWk8hdRR", title: "Lucid Dreams", artist: "Juice WRLD", year: 2018 },
  { id: "7n6elf6gl4POlFO2LlyIMy", title: "בסיבוב הבא", artist: "עדן בן זקן", year: 2018 },
  { id: "7ibWPuw6aT2Vb0hoDUXGHd", title: "יעשו לנו כבוד", artist: "עומר אדם", year: 2018 },
  { id: "4JPoUegxFjxtUgHUcLzoYN", title: "פילטרים יפים", artist: "עדן בן זקן", year: 2018 },
  { id: "2XU0oxnq2qxCpomAAuJY8K", title: "Dance Monkey", artist: "Tones and I", year: 2019 },
  { id: "696DnlkuDOXcMAnKlTgXXK", title: "ROXANNE", artist: "Arizona Zervas", year: 2019 },
  { id: "7k4t7uLgtOxPwTpFmtJNTY", title: "Tusa", artist: "KAROL G", year: 2019 },
  { id: "2b8fOow8UzyDFAE27YhOZM", title: "Memories", artist: "Maroon 5", year: 2019 },
  { id: "0sf12qNH5qcw8qpgymFOqD", title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { id: "21jGcNKet2qwijlDFuPiPb", title: "Circles", artist: "Post Malone", year: 2019 },
  { id: "0nbXyq5TXYPCO7pr3N8S4I", title: "The Box", artist: "Roddy Ricch", year: 2019 },
  { id: "3ZCTVFBt2Brf31RLEnCkWJ", title: "everything i wanted", artist: "Billie Eilish", year: 2019 },
  { id: "6WrI0LAC5M1Rw2MnX2ZvEg", title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
  { id: "6cy3ki60hLwimwIje7tALf", title: "RITMO (Bad Boys For Life)", artist: "The Black Eyed Peas", year: 2019 },
  { id: "2Fxmhks0bxGSBdJ92vM42m", title: "bad guy", artist: "Billie Eilish", year: 2019 },
  { id: "2tnVG71enUj33Ic2nFN6kZ", title: "Ride It", artist: "Regard", year: 2019 },
  { id: "7qEHsqek33rTcFNT9PFqLf", title: "Someone You Loved", artist: "Lewis Capaldi", year: 2019 },
  { id: "3eekarcy7kvN4yt5ZFzltW", title: "HIGHEST IN THE ROOM", artist: "Travis Scott", year: 2019 },
  { id: "7aiClxsDWFRQ0Kzk5KI5ku", title: "hot girl bummer", artist: "blackbear", year: 2019 },
  { id: "3yOlyBJuViE2YSGn3nVE1K", title: "My Oh My (feat. DaBaby)", artist: "Camila Cabello", year: 2019 },
  { id: "2ksOAxtIxY8yElEWw8RhgK", title: "China", artist: "Anuel AA", year: 2019 },
  { id: "0TK2YIli7K1leLovkQiNik", title: "Señorita", artist: "Shawn Mendes", year: 2019 },
  { id: "57vxBYXtHMk6H1aD29V7PU", title: "Heartless", artist: "The Weeknd", year: 2019 },
  { id: "1HfMVBKM75vxSfsQ5VefZ5", title: "Lose You To Love Me", artist: "Selena Gomez", year: 2019 },
  { id: "6Ozh9Ok6h4Oi1wUSLtBseN", title: "BOP", artist: "DaBaby", year: 2019 },
  { id: "5DxXgozhkPLgrbKFY91w0c", title: "Vete", artist: "Bad Bunny", year: 2019 },
  { id: "6Gg1gjgKi2AK4e0qzsR7sd", title: "Bandit (with YoungBoy Never Broke Again)", artist: "Juice WRLD", year: 2019 },
  { id: "5ZULALImTm80tzUbYQYM9d", title: "Dance Monkey", artist: "Tones and I", year: 2019 },
  { id: "6mAN61JH0dzyZpWslS11jy", title: "Fantasias", artist: "Rauw Alejandro", year: 2019 },
  { id: "3VyjsVV24RmBIbWJAeUJNu", title: "No Idea", artist: "Don Toliver", year: 2019 },
  { id: "1hTth4TFnHWYWiXglQ6bN2", title: "רחוק מכולם", artist: "עומר אדם", year: 2019 },
  { id: "5L9qCjY83hVP24RIo3rFjZ", title: "קוקוריקו", artist: "עדן בן זקן", year: 2019 },
  { id: "0SMDtYt5HghaTMFc61nCnP", title: "ואיך שלא", artist: "עומר אדם", year: 2019 },
  { id: "7ea31KGrIuCRvHF31ir6GD", title: "לזאת שניצחה", artist: "עדן בן זקן", year: 2019 },
  { id: "41L3O37CECZt3N7ziG2z7l", title: "Yummy", artist: "Justin Bieber", year: 2020 },
  { id: "5yY9lUy8nbvjM1Uyo1Uqoc", title: "Life Is Good (feat. Drake)", artist: "Future", year: 2020 },
  { id: "7HMmFQsKsljwTw8bS7lu19", title: "Rare", artist: "Selena Gomez", year: 2020 },
  { id: "3ClBKQkKoaUQ6UOhe2xlJK", title: "Good News", artist: "Mac Miller", year: 2020 },
  { id: "2usxQITOSDqvkYiI0oIwao", title: "You should be sad", artist: "Halsey", year: 2020 },
  { id: "4l0Mvzj72xxOpRrp6h8nHi", title: "Lose You To Love Me", artist: "Selena Gomez", year: 2020 },
  { id: "1ToprX3cpBiXoAe5eNSk74", title: "Eleven", artist: "Khalid", year: 2020 },
  { id: "3mQ6SLdxxaL52Yte7KF2Ks", title: "Morado", artist: "J Balvin", year: 2020 },
  { id: "4VgYtXCVJ7IbWAZ5ryfvEQ", title: "Muévelo", artist: "Nicky Jam", year: 2020 },
  { id: "2u3EyuCqqV31woqGvO9LBz", title: "Sum 2 Prove", artist: "Lil Baby", year: 2020 },
  { id: "11OwAR3GlBj9E35Cznf7Lj", title: "Vulnerable", artist: "Selena Gomez", year: 2020 },
  { id: "7FIWs0pqAYbP91WWM0vlTQ", title: "Godzilla (feat. Juice WRLD)", artist: "Eminem", year: 2020 },
  { id: "7GCVboEDzfL3NKp1NrAgHR", title: "Wrong Direction", artist: "Hailee Steinfeld", year: 2020 },
  { id: "4Hqh0dS4x07zuRw6eBTO7p", title: "20/20", artist: "Lil Tjay", year: 2020 },
  { id: "70zg99pT51vB4wlMS7e4q7", title: "La Playa - Remix", artist: "Myke Towers", year: 2020 },
  { id: "5Xhqh4lwJPtMUTsdBztN1a", title: "Me Gusta", artist: "Shakira", year: 2020 },
  { id: "5sK3o66yupTNIK6gWgzGjf", title: "Dance Again", artist: "Selena Gomez", year: 2020 },
  { id: "3vUc9WQpoca15404jNdzf9", title: "Changes", artist: "Lauv", year: 2020 },
  { id: "0PQsrLxPbOBBwwmXCnGvcF", title: "Diamonds (with Normani)", artist: "Megan Thee Stallion", year: 2020 },
  { id: "36J10AwMabBYxgNrV2S8gd", title: "6AM.........", artist: "Dardan", year: 2020 },
  { id: "5NYzvVxuyXiHSqn7PojgKC", title: "Ich hol dich ab", artist: "Jamule", year: 2020 },
  { id: "0VSzREd1OjEWJ9tXoFHRQH", title: "Those Kinda Nights (feat. Ed Sheeran)", artist: "Eminem", year: 2020 },
  { id: "5SiZJoLXp3WOl3J4C8IK0d", title: "Darkness", artist: "Eminem", year: 2020 },
  { id: "61ZM92T2zaXIVsqncThQzC", title: "In Your Eyes (feat. Alida)", artist: "Robin Schulz", year: 2020 },
  { id: "44GSjYhBxuuKx0ikN5Dmag", title: "יהיה טוב & מים שקופים", artist: "עומר אדם", year: 2020 },
  { id: "52wQnuYSGb6DofAGQNLMsa", title: "תזיזו", artist: "עדן בן זקן", year: 2020 },
  { id: "18YUiBqnHhzsRr0k1ppP18", title: "תל אביב בלילה", artist: "עדן בן זקן", year: 2020 },
  { id: "0sCN2Vt33MyAmsHpNxR2Kq", title: "חיים מאושרים", artist: "עדן בן זקן", year: 2021 },
  { id: "3pTsE064ZTJ1n8bP3VAm2c", title: "תהום", artist: "עומר אדם", year: 2021 },
  { id: "1BKXM5acD2NHjBaWTCsXFk", title: "מהפכה של שמחה", artist: "עומר אדם", year: 2022 },
  { id: "5liIuoKq6hJZOheB95eTCt", title: "אגרוף", artist: "עדן בן זקן", year: 2022 },
  { id: "5ArZAXZjGqDC95HySnhvN3", title: "חיים שלי", artist: "עדן בן זקן", year: 2022 },
  { id: "5aDaDlIrhFeXUPcBqxGisR", title: "אחרי כל השנים", artist: "עומר אדם", year: 2023 },
  { id: "5gmwl9W6Ym0JMEgkUPtXe6", title: "יאסו", artist: "עדן בן זקן", year: 2023 },
  { id: "4JSUFLR3Uo7FPCfNDRxIrx", title: "ברחובות של תל אביב", artist: "עדן בן זקן", year: 2023 },
  { id: "3U1voPJN8NBSR96Ry0WJiF", title: "מלכת הדור", artist: "עומר אדם", year: 2024 },
  { id: "5Sn3aXG5AWFmd1ij2PTisj", title: "השיר שאת אהבת", artist: "עומר אדם", year: 2024 },
  { id: "6Ma5wr8hndGkkjsk9rgVKS", title: "היא לא יודעת למה", artist: "Peer Tasi", year: 2024 },
  { id: "3Dx920qUWdBswFizsT1PxR", title: "באמת של האמת", artist: "Osher Cohen", year: 2024 },
  { id: "05iw1Zb7Lp5DNUSvDhBRk6", title: "נגנב ממך", artist: "Full Trunk", year: 2024 },
  { id: "4WoKmBYVGyrf7t0SkHhMQ1", title: "אין כבוד", artist: "Osher Cohen", year: 2024 },
  { id: "6Gt2PGz5zL9HnnJo3UvDV4", title: "עולם בשני צבעים", artist: "ששון שאולוב", year: 2024 },
  { id: "6VYbnnpUYShqFn22MERtmP", title: "המבט בעיניך", artist: "Agam Buhbut", year: 2024 },
  { id: "7iepAdmAykL8gh7dYMzpsM", title: "רולקס וקסקט", artist: "עדן בן זקן", year: 2025 },
  { id: "3gdSZLWC594njZXkwWh7lQ", title: "ואן דאם", artist: "Odeya", year: 2025 },
  { id: "6FVNMp4r4cQOcckK5NFB6j", title: "אם את כבר הולכת", artist: "נדב חנציס", year: 2025 },
  { id: "02mgxr6NgCwAVtuLtttDUB", title: "מדאם", artist: "Noam Bettan", year: 2025 },
  { id: "2bzhJBao5xywL3jlXu2S8O", title: "סחרחורות", artist: "Mor", year: 2025 },
  { id: "7nCe56CzvRKGqTIs5k1dYm", title: "עוף מוזר", artist: "Peer Tasi", year: 2025 },
  { id: "3XSSUNQJHy7GTWtSHHITq5", title: "השם ירחם", artist: "Tuna", year: 2025 }
];
